### ISSUE TITLE
Improvement: Nightwatch-API does not update Nightwatch internal currentTest object per test

### ISSUE THREAD

**Issue by dkurucz** [mucsi96/nightwatch-api#110]
## Expected Behavior

Context: running a typical server setup pattern that uses Cucumber BeforeAll, pretty much as described in your Cucumber integration sample.

When running through a suite of tests orchestrated through createSession in Nightwatch-API, the Nightwatch internal currentTest object is not updated as tests in the suite are traversed.  While this isn't critical to running Nightwatch-API and executing through Cucumber-JS, as Cucumber-JS's own runner is what is doing the heavy lifting, it is a requirement for other libraries that pull currentTest data from the Nightwatch instance such as https://github.com/Crunch-io/nightwatch-vrt.

## Current Behavior

The currentTest is initialized once through createSession but set to a blank object using the default constructor.  The test context never has a chance to change or update as the tests are executed.  Past that point, from what I can tell, there is no way to hook into the Nightwatch instance directly to update the current test context, even if this would be essentially utilizing the Nightwatch internal runner object to serve as a proxy to other plugins.

## Possible Solution

This issue might be solved through some carefully constructed Before clauses.  The easiest solution is to expose a variable through Nightwatch-API that will give direct access to the Nightwatch instance, rather than just the API object, or return the Nightwatch instance through createSession.  With this approach, I could easily add a Before clause that updates the Nightwatch internal test data with the Cucumber test data passed into the Before.

A more complex solution would involve the session itself listening for a test complete or change in test callback that would then invoke setCurrentTest or some related utility method in Nightwatch.

## Context

I understand that the real goal of Nightwatch-API is to be agnostic to Nightwatch's internal runner, however, this limits the usability of some very awesome Nightwatch plugins (such as Nightwatch-VRT) and the work that others have done in the open source community, adding their own awesome asserts, etc.  By leaving control of these specific edge cases to the creativity of the developers putting everything together, I feel Nightwatch-API can solve that many more problems in real-world scenarios.

Thanks for any insight you may have, and keep up the good work with Nightwatch-API!

## Your Environment

- Version used: latest
- Browser Name and version: Chrome latest
- Operating System and version (desktop or mobile): OSX Mojave

**Comment by spnraju** [comment]
Hi @dkurucz , Thank you for reporting the issue with details. We will investigate it.

**Comment by mucsi96** [comment]
@dkurucz Thanks for creating this issue. I love VRT and I completely agree with you suggestions. Maybe some day we can add an out of the box support for it here or just write a documentation section how can it be integrated. But unfortunately we don't have capacity for such a change now. We have a lot to improve on the documentation. If you feel that you can solve it we would be happy to receive a contribution from your side in form of pull request. For now I am closing this.

**Comment by dkurucz** [comment]
@mucsi96 thanks for taking the time to review the issue.  In my observations, this goes beyond VRT testing, and would be essential for any plugin or assertion that needs access to internal Nightwatch runtime variables, properties, and settings.

I am happy to take a look for a way to solve this problem, however, for me to start on an approach, I would like to know the official direction you would like to take Nightwatch-API.  Do you want Nightwatch completely abstracted in this library?  Or would you be okay with Nightwatch-API granting access to the internals of certain aspects (or maybe simply everything) of the library as it is running through the test suites?

If you keep this issue open and add a help wanted label and/or task for this, and provide an official overarching goal or objective for the library in relation to this ask, this would give the community as well as myself an indicator that you are open to a solution as well as a direction you would be open to accepting.

Thanks for your time!

**Comment by spnraju** [comment]
Hi @dkurucz , we have discussed about this and understood that this is how it works when executed through cucumberjs. Please let us know your thoughts.

**Comment by mucsi96** [comment]
@dkurucz The main goal of this package is to separate the "runner" from the "client" and give the users a promise based client they can use with any test runner. Also they can use it without runner as well (take a screenshot of a website or scrape some data from it) Updating the internal objects of Nightwatch test runner is not something we can do here.

**Comment by dkurucz** [comment]
@spnraju @mucsi96 thanks for providing a stance on this.  As a promise-based client that is meant to abstract the details of hooking in runners to Nightwatch, I can definitely see an argument for either direction, and the direction you want to take with this makes a good deal of sense.

My thoughts are the following: when your goal as a client is to orchestrate the connection between any runner and Nightwatch itself, you separate control from the invoker (the developer code) and the engine itself and establish convention, specifically to the scope of what the client is designed to do.  At this point, based on your responses above, the original ask is beyond the scope of the client, but there is no workaround for the extended usage of the Nightwatch framework features needed for finer control of testing, for example, using plugins that integrate with the Nightwatch instance directly and have no visibility into Nightwatch-API.  Therefore, the only solution, short of having Nightwatch-API cover all grounds of execution of a Nightwatch instance under as many predicted scenarios as possible, is to give the developer the necessary control using the same Nightwatch instance used by Nightwatch-API.  This will allow developers to benefit from the work of Nightwatch-API while enabling coverage of more specific needs.

The pattern to do this already exists (use the before and after blocks), the mechanism however is absent, since it is not possible to use both Nightwatch-API and a native Nightwatch instance in the same test execution originally spawned by Nightwatch-API.  At least, this is from what I can tell.  I am not a typescript expert, but in my attempts to manipulate the Nightwatch runtime itself using the exports that Nightwatch-API provides, I was unsuccessful.

I would therefore like to propose that Nightwatch-API somehow expose its runtime Nightwatch instance such that developers can invoke methods such as setCurrentTest and provide their own context and testsuite objects.  I personally feel this would be extremely necessary for anyone in my situation, using Cucumber + Nightwatch outside of its boilerplate functionality.  One benefit I see on both sides is long-term, enough devs use the same techniques often enough that patterns can be migrated into Nightwatch-API for more streamlined development.

Unless of course, anyone else has any better ideas?  If it helps, I'll see if I can provide a concrete example in code to help illustrate the end goal.

Thanks!

**Comment by mucsi96** [comment]
Because of separation of runner and client Testcase and testsuite related parts of Nightwatch are omitted when you are using this package. Event if we provide the Nightwatch instance for outside it will not work as expected as we are directly calling some core methods of Nightwatch. Because of that the instance is not in the same state as it would be with running the tests with pure Nigthwatch. You should search a plugin for the runner you are using. If that's for example Cucumber then use some Cucumber plugin for doing VRT or just use the Cucumber hooks to call some general VRT library. Hope this helps.
