### ISSUE TITLE
Examples are failing with **Error: connect ECONNREFUSED 127.0.0.1:4444**

### ISSUE THREAD

**Issue by spnraju** [mucsi96/nightwatch-api#12]
Thank you for all the great work!

## Expected Behavior
Examples should run without any issues

## Current Behavior
Examples are failing with **Error: connect ECONNREFUSED 127.0.0.1:4444**

## Possible Solution
Could be an issue with Nightwatch version? Tried to update the version to 1.0.8 and faced the same problem

## Steps to Reproduce (for bugs)
1. git clone this repo
2. cd into any of the example folder
3. npm i
4. npm run test

## Context
I was trying to check how this works with cucumber. I had the same issue with Jest as well.

## Your Environment
* Version used: master branch
* Browser Name and version: chrome
* Operating System and version (desktop or mobile): desktop  windows 10
* Link to your project:

**Comment by mucsi96** [comment]
Sorry its not well documented. You have to run ‘npm run ci’. As ‘npm test’ runs only the tests itself, but doesn’t start the tested application and the webdriver

**Comment by spnraju** [comment]
thank you so much @mucsi96. I should have tried this option before opening this issue.

**Comment by mucsi96** [comment]
No no. It very good that you raised it. I have to improve the docs and make it more clear

**Comment by spnraju** [comment]
hi @mucsi96 , Thank you so much for your contribution!

we are using your nightwatch-cucumber for a project. We are planning to move towards this repo. But wanted to check few things before doing so.

1) Any plan on creating a document the migration from old one to this latest one?
2) Is this stable or some enhancements are in plan?

I know this is not the place to ask these questions. but could not avoid as i did not find any other medium.
