### ISSUE TITLE
Are we still be able to use selenium grid?

### ISSUE THREAD

**Issue by expphchen** [mucsi96/nightwatch-api#15]
I am trying out the nightwatch-api and from description, it remove how it was working on the selenium server on the locally, do you have an example on how this can hook up with selenium grid? Thank you nightwatch-api

**Comment by mucsi96** [comment]
Hi currently I don't have setup with selenium grid. But you can search for some selenium grid + Nightwatch setups. It should work the same. Maybe you need to change something because of Nightwatch v1

**Comment by vip30** [comment]
I tested by using selenium/hub docker image.
And it work with nightwatch v1 as expected. Really nice

**Comment by mucsi96** [comment]
Hi @vip30! Thank for checking with nightwatch v1. Can you do a PR with an example. I am sure it would be very helpful for the community 🥇

**Comment by vip30** [comment]
Ok I will try to make a PR

**Comment by vip30** [comment]
https://github.com/mucsi96/nightwatch-api/pull/47

**Comment by expphchen** [comment]
Thanks everyone!
