### ISSUE TITLE
Types definitions

### ISSUE THREAD

**Issue by abianche** [mucsi96/nightwatch-api#16]
Are Typings for TypeScript planned to be supported but Nightwatch-API, or can we just use the ones from Nightwatch (although I couldn't see typings for Page Objects for instance)?

**Comment by mucsi96** [comment]
Are Typing working with Nightwatch v1? If yes it should work here as well. Didn't test.

**Comment by dkoprowski** [comment]
I was trying to use it with Nightwatch types but I wasn't able to configure it properly. Although it looks like types are matching well - just need to connect it with package.

I was doing steps from this exact page: https://stackoverflow.com/a/44796040/7734686

**Comment by spnraju** [comment]
Hi @abianche and @dkoprowski Are we good with this issue? Please close this if it is fixed.

**Comment by spnraju** [comment]
Closing this as there is no further activity.
