### ISSUE TITLE
Can't resolve promise for custom commands functions.

### ISSUE THREAD

**Issue by wartal** [mucsi96/nightwatch-api#17]
When I use custom commands function, then tests stopes after server timeout, due to unresolved promise. It looks like promissify 'commands' is missing in nightwatch-api. 

src: commands/login.js
`exports.command =  function () {
    return this
        .url(...)
        .page.elements()
        .setValue('@loginInput', ...)
        .setValue('@passwordInput', ...)
        .click('@submitButton');
}`

src: steps.js
`Given('...', async () => {
    await client
        .login()
        .page.elements()
        .assert.elementPresent("@mainDiv")
...`

In given scenario, login function will be the only one triggered by nightwatch. Then there will be a server timeout.

Error: function timed out, ensure the promise resolves within 60000 milliseconds

**Comment by wartal** [comment]
It looks like nightwatchjs bug - https://github.com/nightwatchjs/nightwatch/issues/1783
After updating nightwatch from 1.0.6 to 1.0.10 it seems to work.

**Comment by marge2312** [comment]
unfortunately i encounter the same problem with nightwatch version 1.0.14
