### ISSUE TITLE
Feature groups for cucumber-js

### ISSUE THREAD

**Issue by vishalbakshi** [mucsi96/nightwatch-api#175]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

I am working on #173, translating the [Feature Groups](http://mucsi96.github.io/nightwatch-cucumber/#feature-groups) section from the old documentation to the new one.

## Expected Behavior

Appending `-- --group [group name]` to the `npm test` (or equivalent) test command only runs the features in the `[group name]` subfolder if the `script` is `nightwatch`, as shown in the old docs.

I would like to produce the same example for the new documentation for nightwatch-api.

## Current Behavior

I have come across an issue when trying to run tests for feature groups using the example test script given in the [getting started](https://nightwatch-api.netlify.com/cucumber/#step-6-creating-npm-script) section of the new documentation.

After restructuring the example features (google and duckduckgo) into sub-folders:

![image](https://user-images.githubusercontent.com/28925987/52677859-672e0080-2ee4-11e9-9847-d36a601cba70.png)

If I run the following command:

`npm run test:chrome -- --group [name of group]`

cucumber-js still includes all features in the `features` folder.

## Possible Solution

I created a `test` script matching the old docs:

`"test": "nightwatch"`

From what I understand, this requires following the nightwatch-specific [setup](http://nightwatchjs.org/gettingstarted#install-nightwatch) which would deviate from the `nightwatch.conf.js` setup in the new docs.

## Steps to Reproduce (for bugs)

1. Organize features into sub-folders (for example: `google` and `duckduckgo`)
2. Follow all steps in [getting started](https://nightwatch-api.netlify.com/cucumber/#getting-started)
3. Run `npm test:chrome -- --group google`

I receive the following output:

```terminal
vishalbakshi (master *) cucumber-example $ npm run test:chrome -- --group google

> nightwatch-api-cucumber@1.0.0 test:chrome /Users/vishalbakshi/projects/nightwatch-api/packages/cucumber-example
> cross-env browser=chrome npm test "--group" "google"


> nightwatch-api-cucumber@1.0.0 test /Users/vishalbakshi/projects/nightwatch-api/packages/cucumber-example
> cucumber-js --require-module babel-core/register --require cucumber.conf.js --require step-definitions --format node_modules/cucumber-pretty

Feature: DuckDuckGo

  Scenario: Searching DuckDuckGo
    Given I open DuckDuckGo search page
    Then the title is "DuckDuckGo — Privacy, simplified."
✔ Testing if the page title equals "DuckDuckGo — Privacy, simplified."  - 33 ms.
    And the DuckDuckGo search form exists
✔ Testing if element <input[name="q"]> is visible  - 44 ms.

  Scenario: Searching DuckDuckGo again
    Given I open DuckDuckGo search page
    Then the title is "DuckDuckGo — Privacy, simplified."
✔ Testing if the page title equals "DuckDuckGo — Privacy, simplified."  - 18 ms.
    And the DuckDuckGo search form exists
✔ Testing if element <input[name="q"]> is visible  - 32 ms.

Feature: Google Search

  Scenario: Searching Google
    Given I open Google`s search page
    Then the title is "Google"
✔ Testing if the page title equals "Google"  - 14 ms.
    And the Google search form exists
✔ Testing if element <input[name="q"]> is visible  - 57 ms.

  Scenario: Searching Google again
    Given I open Google`s search page
    Then the title is "Google"
✔ Testing if the page title equals "Google"  - 9 ms.
    And the Google search form exists
✔ Testing if element <input[name="q"]> is visible  - 78 ms.

4 scenarios (4 passed)
12 steps (12 passed)
0m06.907s
```
## Context

I would like to come up with an example for nightwatch's feature groups while maintaining a similar configuration as shown in the getting started section of the new documentation. I am not sure if this is possible and am thus reaching out for input/insight.

## Your Environment

- Version used:
  - nightwatch: 1.0.19
  - nightwatch-api: 2.1.1

- Browser Name and version:
   - chromedriver: 2.46.0
- Operating System and version (desktop or mobile):
   - macOS High Sierra 10.13.4
- Link to your project:

**Comment by mucsi96** [comment]
Thanks for your contribution! Let me add some notes why it may not work. The package nightwatch-cucumber was quite hacky it used the nightwatch runner as main and for every single feature file it started the cucumber runner. In this package we completely isolated the „runner“ concept from „client“. Now the user is choosing the runner. The Nightwatch runner itself is not supported. But Cucumber, Jest or Mocha works well. The feature of test group is part of Nightwatch runner. As its not part of Cucumberjs as far as I know we cannot really support that. We create some documentation page describing the architecture of this package for easier contribution. Thanks again!

**Comment by vishalbakshi** [comment]
Sounds good! Thanks for the explanation!

**Comment by spnraju** [comment]
Hi @vishalbakshi you might already know about the tags in cucumberjs and using the same we could be achieveing what you are trying through groups. hope this helps. 

https://www.toolsqa.com/cucumber/cucumber-tags/

**Comment by vishalbakshi** [comment]
@spnraju thank you for the reference I was not aware of that resource. I will look into it.

**Comment by spnraju** [comment]
@vishalbakshi can we close this issue please?

**Comment by vishalbakshi** [comment]
Will do! Thanks.
