### ISSUE TITLE
Failure output is too verbose

### ISSUE THREAD

**Issue by mucsi96** [mucsi96/nightwatch-api#179]
# Steps to reproduce:
- Check out the repository
- Go to `packages/nightwatch-api`
- Run `npm install`
- Run `npm run pack-into-examples`
- Go to `packages/cucumber-example`
- Make the following change in `packages\cucumber-example\step-definitions\steps.js`

![image](https://user-images.githubusercontent.com/3163392/52693149-38586e80-2f66-11e9-8b7f-ed5b8e7dafab.png)

- run`npm test`

![image](https://user-images.githubusercontent.com/3163392/52693074-021aef00-2f66-11e9-8968-4029a9ff26ae.png)

# Actual behavior:
The error output has a lot of duplicates

# Expected behaviour:
Not duplicates should be in the output. Part `Error while running .locateSingleElement() protocol action: no such element: Unable to locate element: {"method":"css selector","selector":"input[name="qsdfdsfsdfds"]"}` should be omitted.

**Comment by spnraju** [comment]
I was trying to replicate this. But was getting error at line 16 of pack-into-examples file on npm run pack-into-examples command. I am on windows 10. Is it because of that?

**Comment by spnraju** [comment]
https://github.com/nightwatchjs/nightwatch/issues/2035

**Comment by mucsi96** [comment]
Great! Thx for your effort. Closing ...
