### ISSUE TITLE
trying to use cucumber example

### ISSUE THREAD

**Issue by psa-vthai** [mucsi96/nightwatch-api#20]
Hi,

I'm trying to use cucumber example.

I have launch npm install and then i launch npm run test:run
i receive these error : 

> cucumber-js --require-module babel-core/register --require test/support --require step-definitions --format node_modules/cucumber-pretty

VError: a BeforeAll hook errored, process exiting: test\support\setup.js:6: function timed out, ensure the promise resolves within 60000 milliseconds
    at c:\User\XXXXX\Workspace\REPOSITORY\Testing\nightwatch\api\examples\cucumber\node_modules\cucumber\src\runtime\index.js:36:15
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (c:\User\XXXXX\Workspace\REPOSITORY\Testing\nightwatch\api\examples\cucumber\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (c:\User\XXXXX\Workspace\REPOSITORY\Testing\nightwatch\api\examples\cucumber\node_modules\bluebird\js\release\generators.js:97:49)
    at Promise._settlePromise (c:\User\XXXXX\Workspace\REPOSITORY\Testing\nightwatch\api\examples\cucumber\node_modules\bluebird\js\release\promise.js:574:26)
    at Promise._settlePromise0 (c:\User\XXXXX\Workspace\REPOSITORY\Testing\nightwatch\api\examples\cucumber\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (c:\User\XXXXX\Workspace\REPOSITORY\Testing\nightwatch\api\examples\cucumber\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (c:\User\XXXXX\Workspace\REPOSITORY\Testing\nightwatch\api\examples\cucumber\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (c:\User\XXXXX\Workspace\REPOSITORY\Testing\nightwatch\api\examples\cucumber\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (c:\User\XXXXX\Workspace\REPOSITORY\Testing\nightwatch\api\examples\cucumber\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
caused by: Error: function timed out, ensure the promise resolves within 60000 milliseconds
    at Timeout._onTimeout (c:\User\XXXXX\Workspace\REPOSITORY\Testing\nightwatch\api\examples\cucumber\node_modules\cucumber\src\user_code_runner.js:61:18)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nightwatch-api-cucumber@1.0.0 test:run: `cucumber-js --require-module babel-core/register --require test/support --require step-definitions --format node_modules/cucumber-pretty`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nightwatch-api-cucumber@1.0.0 test:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XXXXX\AppData\Roaming\npm-cache\_logs\2018-09-07T14_57_57_342Z-debug.log

any idea ?

thanks for your help

**Comment by ErikGrigoriev** [comment]
test:run doesn't work without test:setup. So to check example run "npm run test".

**Comment by psa-vthai** [comment]
ok.
Then when i launch npm run test, i got : 

λ npm run test
> nightwatch-api-cucumber@1.0.0 test c:\User\XXXXXX\Workspace\REPOSITORY\Testing\nightwatch\api\examples\cucumber
> start-server-and-test test:setup http-get://localhost:4444/status test:run

starting server using command "npm run test:setup"
and when url "http-get://localhost:4444/status" is responding
running tests using command "test:run"

> nightwatch-api-cucumber@1.0.0 test:setup c:\User\XXXXX\Workspace\REPOSITORY\Testing\nightwatch\api\examples\cucumber
> babel-node test/server.js

 Timeout while waiting for Selenium Server to start.

May i forget something ?

**Comment by ErikGrigoriev** [comment]
Have you changed something? if yes - please share your changes.

**Comment by pendenaor** [comment]
In my case, the cucumber example works flawlessly, except for the **babel-node** dependency which has to be installed globally.
NB: Tested on Windows 10 + Node 8.4

**Comment by keithpaton** [comment]
Having trouble running the Cucumber Example too. 

When I execute "npm run test", it gets through the test:setup step ok, but then nothing happens at all and it will just hang indefinitely with no further console output.

Any ideas?

**Comment by pendenaor** [comment]
Ok, let me think about it...
In my current code (based on cucumber example), i tweak several things :
**test/server.js** to customize *nightwatch* env
```
import minimist from 'minimist';
import { startWebDriver } from 'nightwatch-api';

const argv = minimist(process.argv.slice(2)) || {}
const env = argv.env || 'default'

startWebDriver(env).catch(err => console.log(err));
```
And **nightwatch.conf.js** to workaround a strange behavior in *nightwatch* (beta 1.0.4) (merge of chrome option args is ... surprising)
```
const chromedriver = require('chromedriver');
const geckodriver = require('geckodriver');

module.exports = {
  custom_assertions_path: ['custom-assertions'],
  custom_commands_path: ['custom-commands'],
  // globals_path: 'nightwatch.globals.js', <== does not work yet, don't use
  test_workers: true,
  detailed_output: false,

  test_settings: {
    "default": {
      webdriver: {
        start_process: true,
        server_path: chromedriver.path,
        cli_args: ['--port=4444']
      },
      desiredCapabilities: {
        browserName: 'chrome',
        javascriptEnabled: true,
        acceptSslCerts: true,
        chromeOptions: {
          args: ['disable-gpu']
        }
      }
    },
    "chrome-headless": {
      webdriver: {
        server_path: chromedriver.path
      },
      desiredCapabilities: {
        browserName: 'chrome',
        javascriptEnabled: true,
        acceptSslCerts: true,
        chromeOptions: {
          args: ['headless', 'disable-gpu']
        }
      }
    },
    "firefox": {
      webdriver: {
        server_path: geckodriver.path
      },
      desiredCapabilities: {
        browserName: 'firefox',
        marionette: true
      }
    }
  }
};
```

And eventually, in my step definitions, i use `defineStep` instead of `Given` `When` `Then`.

Hope it will help you!

**Comment by psa-vthai** [comment]
Hi,
I have deployed a VM on Ubuntu. 
- git clone
- in examples/cucumber, i launched npm install
- then npm run test

it works.

Seems to have some trouble on Windows.
For moment, i do not have explanation.

**Comment by keithpaton** [comment]
@pendenaor thanks! The pointers on config will help me out.

I got the example running on Windows 10, but I thought I would just add my investigations and solution here to help anyone else who has a similar issue.

I think my problem (and maybe it is just a Windows issue) lies in the start-server-and-test package. Or perhaps more specifically the wait-on package it depends on.

If I run `set DEBUG=start-server-and-test && npm run test` in the cucumber example,I can see it get through `test:setup` and then it appears to just sit there forever waiting on a 2XX response from chromedriver. 

The output to the console is just a repeating polling message and this will go on indefinitely until I kill it with ctrl+C.

If I check if chromedriver is running in my browser by visiting http://localhost:4444/status I get the expected status message in the browser and then see then a message for a 503 received by start-server-and-test, but it then continues as before, waiting on a 2XX response that never comes, so it can never move on to `test:run`.

So, I decided to just take start-server-and-run out of the equation and I tweaked test/support/setup.js thus:

```javascript
import minimist from 'minimist';
import { setDefaultTimeout, BeforeAll, AfterAll } from 'cucumber';
import { startWebDriver, stopWebDriver, createSession, closeSession } from 'nightwatch-api';

const argv = minimist(process.argv.slice(2)) || {}
const env = argv.env || 'default';

setDefaultTimeout(60000);

startWebDriver(env).catch(err => console.error(err));

BeforeAll(async () => {
  await createSession(env);
});

AfterAll(async () => {
  await closeSession();
  stopWebDriver().catch(err => console.error(err));
});
```

Now all I need to do is `npm run test:run` and it runs the example, which is enough for what I need to do.

**Comment by pendenaor** [comment]
@keithpaton strange... i don't have to explicitly stop chromedriver.
my scripts in **package.json**
```
 "scripts": {
    "test:setup": "babel-node test/server.js --env=default",
    "test:run": "cucumber-js --tags @automated --require-module babel-core/register --require test/support --require step-definitions",
    "test": "start-server-and-test test:setup http-get://localhost:4444/status test:run"
  },
```

and my dependencies :
```
"devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-preset-env": "^1.7.0",
    "chromedriver": "^2.40.0",
    "cucumber": "^4.2.1",
    "cucumber-pretty": "^1.4.4",
    "geckodriver": "^1.11.0",
    "minimist": "^1.2.0",
    "nightwatch": "1.0.9",
    "nightwatch-api": "^0.4.0",
    "p-wait-for": "^2.0.0",
    "start-server-and-test": "^1.5.0"
  }
```

**Comment by psa-vthai** [comment]
thanks all for help.
Ticket is closed
