### ISSUE TITLE
How to pass command line arguments to nightwatch?

### ISSUE THREAD

**Issue by laberning** [mucsi96/nightwatch-api#22]
Thanks for this great library!
How can we pass command line arguments to nightwatch when using this library?

I.e. I would like to pass --skiptags to nightwatch, but I don't see an option to do so (using the cucumber example). Nightwatch seems to be called/initialized internally via the nightwatch-api library.

**Comment by mucsi96** [comment]
As Nightwatch runner is not used at all you cannot do that. But you can use Cucumber CLI. It has a `--tags` option. See: https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#tags
