### ISSUE TITLE
Add documentation for using nightwatch-api + browserstack

### ISSUE THREAD

**Issue by azinchenko91** [mucsi96/nightwatch-api#220]
Hey Guys, 

is it possible to use nightwatch-api + browserstack?

**Comment by spnraju** [comment]
Hello @azinchenko91 ,

Below are some links which might be of some help to you.

https://www.browserstack.com/automate/cucumberjs
https://github.com/browserstack/cucumber-js-browserstack
https://www.browserstack.com/automate/cucumber-integration
https://www.browserstack.com/automate/cucumberjs

**Comment by mucsi96** [comment]
Using browser stack should be the same as with pure Nightwatch. So you should be able to follow https://www.browserstack.com/automate/nightwatch Please let us now if something is different. Also your contribution to the documentation improvement is very appreciated.
