### ISSUE TITLE
Intellisense/Autocomplete Guide on VS Code

### ISSUE THREAD

**Issue by sumargoraymond** [mucsi96/nightwatch-api#225]
It would be really great to have a guide on how to make autocomplete/intellisense possible on Visual Studio Code for methods invoked on step definitions.

**Page object file** 
```
//Page object file
const { client } = require('nightwatch-api');
const base = require('my-base-page');

const pgHomepage = {
  url() {
    const url = base.setURL('www.google.com');
    return url;
  },
  elements: {
    // label
    labelPage: '.ts-label-productname',
  },
  commands: [{
    navigateToHomepage() {
      base.pauseSleep(client, 2000);
      return base.maxWindow(this.api) && this.navigate();
    },
  }],
};

module.exports = pgHomepage;
```

**Step definition file**
 
```
//Step definition file
const browser = client.page.homepage();

Given(/^user at homepage$/, () => {
//Auto complete not working for method navigateToHomepage();
  browser.navigateToHomepage();
});
```

It is really a bummer that Visual Studio Code fails to parse and show definition of methods called from step definition's page object based. Any guides perhaps to make this possible?

Thanks a lot.

**Comment by spnraju** [comment]
Hi @sumargoraymond , Please note that this is not the right place to seek help on these kind of things. 

https://groups.google.com/forum/#!forum/nightwatchjs and https://stackoverflow.com/questions/tagged/nightwatch.js are more appropriate. 

Having said that, below are some of the links what you are looking for. 

https://marketplace.visualstudio.com/items?itemName=sandeepthukral.nightwatch-js-snippets
https://marketplace.visualstudio.com/items?itemName=Raju.vscode-nightwatchjs-snippets

Thank you for understanding.
