### ISSUE TITLE
Document the usage of custom test reporters with some examples.

### ISSUE THREAD

**Issue by mucsi96** [mucsi96/nightwatch-api#226]
Document for example the usage of Cucumber HTML reporter.

**Comment by flashbackzoo** [comment]
Hi @mucsi96 I have [cucumber-html-reporter](https://www.npmjs.com/package/cucumber-html-reporter) working on my project now.

What sort of documentation would you like? For example I could:

* Add a section to the bottom of [the Cucumber page](https://github.com/mucsi96/nightwatch-api/blob/master/packages/website/src/data/cucumber/index.md).
* Update the existing [Cucumber example](https://github.com/mucsi96/nightwatch-api/tree/master/packages/cucumber-example)
* Create a new example

Let me know what you think.

**Comment by mucsi96** [comment]
Cool! Please add a section to Cucumber page. Thanks a lot!

**Comment by mucsi96** [comment]
Also if possible add a screenshot of the report containing successful, failed and ignored steps

**Comment by flashbackzoo** [comment]
PR https://github.com/mucsi96/nightwatch-api/pull/234
