### ISSUE TITLE
How to run specific cucumber files or tags now?

### ISSUE THREAD

**Issue by rgeraldporter** [mucsi96/nightwatch-api#24]
Hi! I'm cutting over our tests from nightwatch-cucumber to nightwatch-api, but can't seem to find how you can possibly run tests for specific tags or feature files via the CLI.

`start-server-and-test` doesn't support passing arguments at all, so outside of writing a script entry for every single feature file & tag we have, I don't see how to get this to work in the new setup. In `nightwatch-cucumber` it was very easy to do.

## Expected Behavior
assuming you have something like:

```
"test": "start-server-and-test test:setup http-get://localhost:4444/status test:run",
```
Running
`npm run test -- features/something.feature`

or

`npm run test -- -t @my-tag`

## Current Behavior
`Error: expect: <start script name> <url> <test script name>`

(throws errors from start-server-and-test as it doesn't accept any more arguments, let alone passing them along)

## Possible Solution
Not sure. `start-server-and-test` has an open issue about this.

## Context
(see above)

But also, when developing tests its fairly typical to only run the feature files you're actually developing, right now outside of writing a custom script line I don't see how to do it.

## Your Environment
Node 10.10.0, MacOS 10.13.6, used example linked from `nightwatch-cucumber` for updating the deprecated module.

**Comment by mucsi96** [comment]
In development I suggest to run `test:setup` and `test:run` in separate terminals. With that you can achive tow things.
- No server and webdriver restarts with test reexecution
- You can provide addition command line options for Cucumber using `npm run test:run -- -some-options`.
- Using Cucumber CLI options you can run specific feature files or using expressions you can run specific tags

As I have time will describe this somewhere in the migration docs.

**Comment by spnraju** [comment]
@mucsi96 , is there a way we could pass the environment as well through CLI options instead of passing it in server.js and setup.js files of cucumber examples?

**Comment by spnraju** [comment]
Hi @rgeraldporter here is a link which might help you. 

https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#running-specific-features

Closing this for now.

**Comment by gnaneswarreddy** [comment]
Hi @spnraju 

With nightwatch api i am not able to run a specific feature file, i have also tried the cucumber CLI option but i am not able to run using nightwatch-api
I tried cucumber-setup.js features/google.feature command

**Comment by spnraju** [comment]
It should be `cucumber-js features/google-search.feature`.

**Comment by mucsi96** [comment]
I will add this to cucumber docs

**Comment by mucsi96** [comment]
Documentation is updated with filtering feature files and tags

**Comment by neillindberg** [comment]
From running with the "--help" flag I can see there is a "--tags" option, but it doesn't work with using \@sometag, or pointing to a feature file location. Should the flag be removed? I @spnraju 's answer worked for me, but it wasn't apparent.
