### ISSUE TITLE
Nightwatch --env var to multi browser do not run

### ISSUE THREAD

**Issue by mestihudson** [mucsi96/nightwatch-api#247]
## Expected Behavior

Current version of nightwatch I can submit --env firefox,chrome to run with two cited browsers.

## Current Behavior

When I inform env to startWebDriver, it starts only one of two.

## Steps to Reproduce (for bugs)

I has configured environment variable 'browser' (who feeds 'env' attr of settings on 'cucumber.conf.js') with the following value 'firefox,chrome' (like I has did on nightwatch parent project througth '--env firefox,chrome') but just 'firefox' has executed.

## Your Environment

- Version used: 2.1.1
- Browser Name and version: chrome and firefox, (docker image selenium/node-chrome:2.53.1-beryllium selenium/node-firefox:2.53.1-beryllium)
- Operating System and version (desktop or mobile): alpine
- Link to your project: https://github.com/mestihudson/nightwatch-boilerplate/tree/cucumber.

**Comment by spnraju** [comment]
Hi @mestihudson this is the expected behaviour. We will be adding some documentation about why we can not do it that way as part of #227 

Thank you for brining this up.

**Comment by VinceBarresi** [comment]
@spnraju This is unfortunate. Is the alternative method you could recommend to accomplish this using nightwatch-api and cucumberjs?

**Comment by spnraju** [comment]
Hi @VinceBarresi we are trying few things. But as of now, we dont see a way to execute in mutliple browsers. We will definitely add it to our documentation if we are able to.

**Comment by gkushang** [comment]
@spnraju do you have any updates on running Multi Browsers in parallel?

**Comment by spnraju** [comment]
@gkushang Unfortunately, we dont see a way of running the tests in parallel in multiple browsers.
