### ISSUE TITLE
Support for screenshots gone?

### ISSUE THREAD

**Issue by rgeraldporter** [mucsi96/nightwatch-api#25]
I was wondering if the support for screenshots that nightwatch-cucumber is gone now? I can't find any references in this repo and configs that worked in n-c do not work now.

**Comment by rgeraldporter** [comment]
@mucsi96 I had this sort-of-working until I realized the problems with `waitForElement` checks.

This is what I was doing, in `setup.js`

```js
// Passing a callback
After(function(testCase, callback) {
    if (testCase.result.status === Status.FAILED) {
        const world = this;
        const filepath = `./screenshots/${faker.random.uuid()}.png`;
        client.saveScreenshot(filepath, screenshot => {
            try {
                world.attach(screenshot.value, 'image/png', callback);
            } catch(e) {
                callback();
            }
          }
        );
    } else {
        callback();
    }
});
```

Passing the `screenshots` object into `test_settings.default` wasn't doing anything.

**Comment by mucsi96** [comment]
I see. Can you do some deeper investigation on this? I am not at my computer for 2 weeks

**Comment by mucsi96** [comment]
I have created a PR for this. After review we can release it. After that I am waiting for your feedback 👍

**Comment by mucsi96** [comment]
Feature released in `2.1.0`. This is how you can enable it https://nightwatch-api.netlify.com/#screenshots-on-failure

**Comment by gnaneswarreddy** [comment]
I followed the same example in cucumber-example and  one of my step definition for title got failed, still After function has been success and no screenshot is getting saved to the folder. Could anyone help me what is the actual issue i am using cucumber-js, html reporter latest versions and nightwatch api latest version. 

Thanks,
Eswar

**Comment by mucsi96** [comment]
Have you enabled the screenshot creation on failure? Search for screenshot in the docs. Looks like its missing from the cucumber html repoter docs. Will update the docs

**Comment by gnaneswarreddy** [comment]
yes i enabled 

screenshots:{
enabled:true,
path:'to my local drive'
on_failure:true
on_error:true
}

**Comment by mucsi96** [comment]
Then something is wrong with screenshot creation. What path are you using? Maybe there is something about it. Can you try both relative and absolute path. Currently it works fine on my machine and on CI Linux

**Comment by gnaneswarreddy** [comment]
I used both relative and absolute path still not working and below are the versions i am using
nightwatch-api - 2.1.1, cucumber-html-reporter: 4.0.5 and cucumber: 5.1.0 OS: Windows7. Am i missing anything?

**Comment by mucsi96** [comment]
The last think I car recommend is to clone the repo and try to run the examples on your machine. Check if screenshot is created in cucumber example if you make some step failing

**Comment by spnraju** [comment]
Even I have tried with cucumber-example by altering line number 17 as below and found screenshots under screenshots folder.

`await client.assert.visible('input[name="q3423"]');`

**Comment by mucsi96** [comment]
@gnaneswarreddy any updates?

**Comment by gnaneswarreddy** [comment]
I did a small mistake in nightwatch-conf.js and i fixed it now screenshots are loading fine. Thankyou @mucsi96 and @spnraju

**Comment by mucsi96** [comment]
Great! Happy to help! Will add screenshot enabling to html reporting section

**Comment by gnaneswarreddy** [comment]
Hi,
Not sure if its the right forum to post but i am looking to perform a scroll down to a particular element using nightwatch api and perfecto. Is there any code available or please let me know if anyone has done it.

**Comment by spnraju** [comment]
@gnaneswarreddy You are right. This is not the right forum to ask. But just to help you out, check the below URL. 

http://nightwatchjs.org/api/moveToElement.html
http://nightwatchjs.org/api/moveTo.html

**Comment by gnaneswarreddy** [comment]
Hi, 
one small question about screenshots i removed on_failure:true, on_error:true and i was hoping that passed screenshots would be saved to the folder. Am i missing anything? Will the passed screenshots cannot be saved.

**Comment by gnaneswarreddy** [comment]
Hi,
Is the screenshots generated only on failure?

Thanks,
Gnaneswar

**Comment by mucsi96** [comment]
Hi! Unfortunately this is implemented currently to take skip the the successful cases. See https://github.com/mucsi96/nightwatch-api/blob/7db344fc9ad9e9e7393837b93d7d68e787627b21/packages/nightwatch-api/src/client.ts#L137

But it's quite easy to change. Would appreciate if you can contribute and send a pull request for this. Also please create a separate issue for this as this thread is getting too long :)

**Comment by gnaneswarreddy** [comment]
Hi @mucsi96,

Actually i have a laptop which is related to the customer and cannot do the pull request and upload it. I can just use the npm package. Is @spnraju will be able to help as in my personal laptop it will take time to setup with everything?

Thanks.

**Comment by mucsi96** [comment]
Based on Nightwatch docs it also doesn't support auto screenshot creation on success. See

> Selenium generates screenshots when command errors occur. With on_failure set to true, also generates screenshots for failing or erroring tests. These are saved on the disk. 
> Since v0.7.5 you can disable screenshots for command errors by setting "on_error" to false. 
> Example:
```
"screenshots" : {
  "enabled" : true,
  "on_failure" : true,
  "on_error" : false,
  "path" : ""
}
```

But you can manually create screenshot any time.

**Comment by gnaneswarreddy** [comment]
Yes i tried the same way for failure and it was successfully getting saved to disk. But i have to use the screenshots used in pass scenario in cucumber-html-reporter. As you have mentioned if (client && client.api.screenshotsPath) { Can we have the option so that we can also save the screenshots and it automatically be pulled up in reporter framework also?

**Comment by mucsi96** [comment]
When do you want to do the scrrenshots? After every step or after every scenario as last step?

**Comment by gnaneswarreddy** [comment]
after every step if possible

**Comment by mucsi96** [comment]
It's easy to make screenshot after every scenario using cucumber hooks. Unfortunatly the step hook was removed from cucumber. So its harder. Also I dont think we can do much in this package

**Comment by mucsi96** [comment]
This is the issue you can follow https://github.com/cucumber/cucumber-js/issues/997
