### ISSUE TITLE
Suites & steps with commands that fail are reported as passed

### ISSUE THREAD

**Issue by rgeraldporter** [mucsi96/nightwatch-api#26]
## Expected Behavior
calls to Nightwatch commands like `.waitForElementVisible()` and `.click()` should report a step (& suite) failure when they timeout, are unable to click, or other kinds of errors.

## Current Behavior
the failures output to the log but the suite keeps going and everything reports as passing

## Possible Solution
Not sure! Even if I explicitly set `abortOnFailure` in something like `waitForElementVisible` this still happens.

## Steps to Reproduce (for bugs)
I've created a PR just as an example of the bug in action, not meant for the codebase. It takes an example from the Cucumber example and introduces a test that should have a failure, but passes. See changed files for how to generate this bug, and see PR description for output log.

https://github.com/rgeraldporter/nightwatch-api/pull/1

## Context
I was attempting to add screenshots on failure with my own solution from CucumberJs's docs (see previous issue) and discovered I couldn't get screenshots during these kinds of failures because they didn't report to `testCase.result.status` as failed, but as passed.

## Work-around
Add assertions or expects to every step that is only commands, though this is limited to testing for presence/visibility of elements, won't work for things like `.click()`.

I'll keep digging into what might cause it but I don't know if I'll have enough time to dig into this.

## Your Environment
Node v10.10.0, MacOS 10.13.6, Chrome 69

**Comment by psa-vthai** [comment]
Thanks @rgeraldporter.
i have the same issue. so my reports are wrong.
I have wasted time to know which package was in default. with nightwatch 0.9.21, i's OK.

Could you please tell us link to your PR please ?

**Comment by psa-vthai** [comment]
Also do you have an example of Work-around please

**Comment by rgeraldporter** [comment]
@psa-vthai I'll post it once it is up. I have a fix but it breaks a test within Nightwatch so I'm trying to sort that out before opening it up. If I can't figure it out soon I'll post it there as an issue and ask for assistance with that one test.

**Comment by rgeraldporter** [comment]
@psa-vthai the PR is up now. See 
https://github.com/nightwatchjs/nightwatch/pull/1890

**Comment by mucsi96** [comment]
Sounds interesting. How is `.waitForElementVisible()` and `.click()` behaving with pure Nightwatch v1?

**Comment by rgeraldporter** [comment]
@mucsi96 It seems to pass fine as the CLI reporter picks up the error downstream somehow. 

At least, that's what I could determine from fiddling with the unit tests -- within the unit tests as they were, I could create a failure of a test on `waitForElementVisible` but only via methods that mimicked using the CLI.

`.click` remains to be seen, I always do `waitForElement` before a click so it wouldn't be an issue for me but I assume it it also affected. I'll see what the feedback is on this PR first and go from there though!

**Comment by mucsi96** [comment]
Any update on this?

**Comment by rgeraldporter** [comment]
The nightwatch maintainer asked me to check if 1.0.12 fixes, it but I ran the changes in  https://github.com/rgeraldporter/nightwatch-api/pull/1 through the latest version of this repo, pointed at 1.0.12 but it still misses the failure completely.

**Comment by rgeraldporter** [comment]
Reading more into their latest changes, unfortunately it looks like they ignored my PR and my proposed unit tests and refactored the sections of the code that had the bug that I opened a PR for, but without testing to see if it actually fixed the issues. So now my PR doesn't really work any longer, and the bugs are now present with a completely different set of code that is even more complex than before. I'm going to try to parse through it, but it's rather discouraging.

**Comment by spnraju** [comment]
Hi @rgeraldporter Any update on this? If this is an issue with nightwatch itself, would you mind closing this issue?

**Comment by rgeraldporter** [comment]
@spnraju I can close it, though you may end up with others coming here with the same issue. It is still open with Nightwatch, still an issue in their latest version, and I don't really understand why they don't take test falsification issues seriously. 🤷‍♂️
