### ISSUE TITLE
attach screenshot to cucumber report

### ISSUE THREAD

**Issue by tehjape** [mucsi96/nightwatch-api#287]
saving screenshots in nightwatch-cucumber would [attach the image](https://github.com/mucsi96/nightwatch-cucumber/blob/master/lib/nightwatch-api.js#L157-L160) to the cucumber report. nightwatch-api will save a screenshot (with the template `[date]-[time]-[ms].png`), but how can the data be embedded into the cucumber report like nightwatch-cucumber does?

**Comment by mucsi96** [comment]
Attaching of screenshots added to the docs, also example updated https://nightwatch-api.netlify.com/cucumber/#custom-reporters
