### ISSUE TITLE
Chrome Version 73.0.3683.67, Failed to supporting the click function

### ISSUE THREAD

**Issue by AbinayaPalani** [mucsi96/nightwatch-api#293]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Steps to Reproduce (for bugs)

1. 2. 3. 4.

## Your Environment

- Version used:
- Browser Name and version:
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by AbinayaPalani** [comment]
Getting element is not clickable at the point. When I checked in npm package, seems like doesn't update the chrome driver.
Still it is chrome driver 2.46

**Comment by mucsi96** [comment]
Please use the issue template as we need all the details for anyone be able to pick up the issue

**Comment by mucsi96** [comment]
Please create a new issue following the issue template. Closing this one
