### ISSUE TITLE
When a `globals` object or a `globals_path` string is set it fails to `createSession()`

### ISSUE THREAD

**Issue by mAiNiNfEcTiOn** [mucsi96/nightwatch-api#3]
## Expected Behavior
I should be able to set the `globals` or `globals_path` properties in the `nightwatch.conf.js`.

## Current Behavior
Based on your configuration in the cucumber example, I added a `globals_path` property, properly configured. Resulted in Nightwatch not being able to create a session.

Same for setting a `globals` object to override the default globals. Nope, didn't work either.

## Possible Solution
I don't know for sure, but I think this is related to the fact that, in `nightwatch@1.0.6`, the platform is using lodash's merge to combine one object to another, but unfortunately that object's properties and their sub-properties are observed via the usage of `Proxy`. So the merge fails to happen, apparently.

## Steps to Reproduce (for bugs)
1. Add `globals_path` and/or `globals` property to the `nightwatch.config.js`
2. Run `yarn ci` (or `yarn start && yarn test`)
3. You should see the error in your console

## Context
Well, I was trying to implement cucumber on top of `nightwatch`, using your project. 

Btw, if I use your config as is, it works well 👍 

## My Environment
* Version used: 0.4.0
* Operating System and version (desktop or mobile): MacOS HighSierra 10.13.4 (Desktop)

@mucsi96 thank you so much for developing this layer on top of `nightwatch`. Really helpful, great work!

**Comment by mucsi96** [comment]
Thx for your detailed feedback. Will do a short investigation on the topic

**Comment by mucsi96** [comment]
Sorry for really long response time. I have tried to reproduce the issue without any luck. It is working for me fine. I have created a test case as well. See: https://github.com/mucsi96/nightwatch-api/pull/8

**Comment by mAiNiNfEcTiOn** [comment]
@mucsi96 thanks 👍Will see my side then. Been a little bit away from it.
