### ISSUE TITLE
Is there any plan to support TS?

### ISSUE THREAD

**Issue by liuhaitao827** [mucsi96/nightwatch-api#395]
Seems the package don't support TypeScript now. Is there any plan to support TS?

**Comment by mucsi96** [comment]
This package is written in TS and provides typings as well. But brobably your issue is with the typings for Nightwatch client.

**Comment by delfin86** [comment]
https://github.com/AsadHasan/NightWatchTypescriptTesting

Hey! mb try to integrate that in our project?

**Comment by mucsi96** [comment]
Ist it a problem that the version of types has different major version that the nightwatch?

**Comment by delfin86** [comment]
don't have any clue (( Need to try)

**Comment by delfin86** [comment]
Just need fix files nightwatch.json and update package.json and it will work
nightwatch.json
---------------------------
{
  "src_folders": ["Tests"],
  "page_objects_path": "PageObjects",
  "webdriver": {
    "start_process": true,
    "server_path": "node_modules/chromedriver/bin/chromedriver",
    "port": 9515
  },
  "test_settings": {
    "default": {
      "launch_url": "https://www.gumtree.com/",
      "props": {
        "name": "Homepage"
      },
      "desiredCapabilities": {
        "browserName": "chrome"
      }
    }
  }
}

For package.json we need to update dependencies: 
    "@types/nightwatch": "^1.1.0",
    "nightwatch": "^1.1.12"
![Screenshot from 2019-06-20 13-19-32](https://user-images.githubusercontent.com/46029957/59841933-1466c880-935e-11e9-991c-9c59e86e769a.png)

What thoughts?

**Comment by mucsi96** [comment]
Cool. The other issue I see with Typescript and nightwatch-api that nightwatch-api promisifys every api call which will require a completely different api types. Is it possible with TypeScript to base the types on @types/nightwatch but make every api method return a chainable promise? I hate that we are mixing chaining and promises but this is what we have now :/

**Comment by delfin86** [comment]
Take a look
https://github.com/aamorozov/nightwatch-setup-ts/blob/master/src/types/index.d.ts
I guess need to view that and wind a way integrate into nightwatch-api.
