### ISSUE TITLE
cucumberArgs

### ISSUE THREAD

**Issue by coryellcp** [mucsi96/nightwatch-api#4]
I'm upgrading from nightwatch-cucumber. Is there still support for passing in additional arguments to Cucumber.js?

This was formerly done with the cucumberArgs object.

**Comment by mucsi96** [comment]
In this package the runner should be cucumber.js itself. So no need to pass cucumberArgs as you directly run the stuff with cucumber

**Comment by eternityCoder1** [comment]
how to pass arguments to cucumber.js in Nightwatch-API package?
earlier we used to pass it as below:
require('nightwatch-api')({
    cucumberArgs: ['--require', 'hooks.js', '--require', 'timeout.js', '--require', 'step_definitions', '--format', 'json:reports/cucumber.json', 'features'],
    nightwatchOutput: false
});
