### ISSUE TITLE
TypeError: Cannot read property 'api' of undefined - Page Object Error

### ISSUE THREAD

**Issue by gkushang** [mucsi96/nightwatch-api#421]
Adding a Page Object in existing `cucumber-selenium-example` package has below error. Also, does not work on another project I'm working on. 

Bug can be reproduced at git@github.com:gkushang/nightwatch-api.git:feature/api-error
1. $ git clone git@github.com:gkushang/nightwatch-api.git
2. Switch to branch `feature/api-error`
3. $ npm i
4. $ cd packages/cucumber-selenium-example
5. $ npm i
6. $ npm run test:chrome

**Error is below**

```
1) Scenario: Searching Google # features/google-search.feature:3
   ✖ Given I open Google`s search page # step_definitions/steps.js:4
       TypeError: Cannot read property 'api' of undefined
           at Proxy.login (/Users/kgajjar/Documents/workspace/Salesforce/nightwatch-api/packages/cucumber-selenium-example/pages/login_page.js:14:18)
           at World.<anonymous> (/Users/kgajjar/Documents/workspace/Salesforce/nightwatch-api/packages/cucumber-selenium-example/step_definitions/steps.js:6:19)
   - Then the title is "Google" # step_definitions/steps.js:14
   - And the Google search form exists # step_definitions/steps.js:18
```
```
module.exports = {
  custom_assertions_path: 'custom-assertions',
  page_objects_path: 'pages',
  test_settings: {
    default: { ...
```
login_page object:
```
module.exports = {

    elements: {
        username: 'input[type=text]',
        password: 'input[type=password]',
        login_button: 'button[name=login]'
    },
    commands: [{
        login: () => {
            return this.api.pause(1000);
        }
    }]
};
```

versions: 
"nightwatch": "^1.0.19",
"nightwatch-api": "latest",

**Comment by spnraju** [comment]
Hi @gkushang Thank you for reporting this. I remember encountering this somewhere. I made your tests work by simply replacing the `login: () => {` with `login: function () {`. I have heard from someone that `this` will not work inside arrow functions. Maybe because of that. Please let us know if you have any further questions.

**Comment by spnraju** [comment]
https://stackoverflow.com/questions/44080949/value-of-this-inside-arrow-function-inside-an-object

**Comment by gkushang** [comment]
Great, it works! Thank you for the explanation 👍
