### ISSUE TITLE
Any way to override the reporter or silence it?

### ISSUE THREAD

**Issue by darrinholst** [mucsi96/nightwatch-api#434]
## Expected Behavior

Should be able to control what gets emitted to the console.

## Current Behavior

Passed assertions write to stdout with no way to override?

## Possible Solution

Remove writing to stdout and rely on the underlying runner to output as described in #217.

## Context

I use a progress bar for cucumber. This behavior breaks that.

![F80855EF-64B1-44A3-95DB-306EC726080B](https://user-images.githubusercontent.com/4854/56508020-c0b83a00-64e8-11e9-82e6-fa2f4b7517ae.png)

**Comment by mucsi96** [comment]
Good point. We would appreciate a pull request fixing this.

**Comment by mucsi96** [comment]
The new `silent` option is released as part under version `2.2.0`

**Comment by darrinholst** [comment]
👍 thanks!
