### ISSUE TITLE
stopWebDriver does not end the process

### ISSUE THREAD

**Issue by zeeshan1001** [mucsi96/nightwatch-api#44]
The node process which runs the web driver keeps running even after stopWebDriver() is called. I had to end it like this. I cannot use this in a CI process until the process ends. This is happening in your cucumber example also but you link to the SIGTERM signal to avoid this.

var BeforeAll = require('cucumber').BeforeAll;
var AfterAll = require('cucumber').AfterAll;
var createSession = require('nightwatch-api').createSession;
var closeSession = require('nightwatch-api').closeSession;
var startWebDriver = require('nightwatch-api').startWebDriver;
var stopWebDriver = require('nightwatch-api').stopWebDriver;

BeforeAll(async () => {
  startWebDriver('default').catch(err => console.log(err));
  await createSession({ env: 'default' });
});

AfterAll(() => {
  closeSession()
  stopWebDriver(); // This line executes but does not stop the web driver. The process keeps on running.
});

**Comment by sergeisomething** [comment]
I think thats similar to my issue and I still didn't find the solution except manually exiting the process
https://github.com/mucsi96/nightwatch-api/issues/38

**Comment by mucsi96** [comment]
@zeeshan1001 @sergeisomething Thanks for your feedback! Can you do some investigation why the process is hanging? A pull request would be very appreciated 🥇

**Comment by spnraju** [comment]
Hi @zeeshan1001 and @sergeisomething , are you still facing this issue? If not, could you let us know what fixed the issue?

**Comment by mucsi96** [comment]
Version 2.1.1 is release which fixes a bug found with closing the session. Maybe it solves this issue as well. We have added test to our CI which makes sure that after every test execution the WebDriver is stopped properly. Closing for now. Feel free to reopen if the issue still exist
