### ISSUE TITLE
Feature file starts executing before the "beforeAll" hook completes its execution! 

### ISSUE THREAD

**Issue by ajinkyabhuruk1996** [mucsi96/nightwatch-api#440]
## Expected Behavior

I have cucumber.conf.js in which I have mentioned BeforeAll hook.  I have configure some custom command which executes some steps and takes some time to execute.

My command code is like below:
 var util = require('util');
var events = require('events');
import appconfig from '../appconfig';
import { client } from 'nightwatch-api';
function doSomeStep () {}
util.inherits(doSomeStep, events.EventEmitter);
doSomeStep.prototype.command = function () {
    client.element('css selector', 'input[name=loginfmt][type=email]', function(result){
        if (result.value && result.value.ELEMENT) {
            // Element is present, do the appropriate tests
            client.setValue('input[name=loginfmt][type=email]', appconfig.username) 
                .click('input[type=submit][id=idSIButton9]')      
                .pause(5000);               
        } else {
            // Element is not present.
        }
    });
    this.emit('complete');    
};
module.exports = doSomeStep;

And cucumber config file :

BeforeAll(async () => {
await startWebDriver({ env: process.env.NIGHTWATCH_ENV || 'chromeHeadless' });
await createSession();
await client.url('http://google.com');
try{
await client.doSomeStep();
}
catch(ex){
console.error('We got below error while executing the step');
console.log(ex.message);
}
});

## Current Behavior

Features written in cucumber gets executed before the "beforeAll" hook completes its execution. 

## Possible Solution

None of the features should get execute before the "beforeAll" hook executes.

## Your Environment

- Version used: 
    "nightwatch": "^1.1.3",
    "nightwatch-api": "^2.1.4",
- Browser Name and version: Chrome

**Comment by ajinkyabhuruk1996** [comment]
Steps get executed before the "BeforeAll" hook of cucumber in cucumber configuration file. 

BeforeAll(async () => {
  await startWebDriver({ env: process.env.NIGHTWATCH_ENV || 'chromeHeadless' });
  await createSession();
  await client.url('http://google.com');
    try{
      await client.doSomeStep();  
    }
    catch(ex){
      console.error('We got below error while executing the step');
      console.log(ex.message);     
    }  
  });

**Comment by mucsi96** [comment]
Thank for your feedback! Can we ask you to use the issue template? It will clarify all information needed for anyone willing pick this up.

Also can you write down why you think that steps are executed before the beforeAll hook. From issue description it's impossible to see that's true.

**Comment by ajinkyabhuruk1996** [comment]
Thanks Musci. :) I moved logic to feature file . I guess I got this issue because there was some manual intervention required while running automated tests. So closing issue for now.
