### ISSUE TITLE
Any generic function like takeScreenshot() in protractor can be implemented in nightwatch api?

### ISSUE THREAD

**Issue by gnaneswarreddy** [mucsi96/nightwatch-api#441]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Steps to Reproduce (for bugs)

1. 2. 3. 4.

## Your Environment

- Version used:
- Browser Name and version:
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by spnraju** [comment]
Not sure what is that you are talking about as none of us have used protractor. Please add more details when you raise an issue.
