### ISSUE TITLE
client.getAttribute() not returning promise, times out when using cucumber

### ISSUE THREAD

**Issue by rgeraldporter** [mucsi96/nightwatch-api#472]
I'm giving an upgrade to Nightwatch v1 a try again, going better this time, but getting stuck on at least one command.

Using the cucumber-example folder to recreate the problem, take this step and modify it:

```
Then(/^the title is "(.*?)"$/, async text => {
  await client.getAttribute(
    'body',
    'id',
    result => client.assert.equal('pg-index', result.value)
  );
});
```
(yes, not a title any more, but title tag has no attributes on DDG)

It seems this never resolves the promise with a failure or a pass, and thus cucumber eventually gives a promise timeout error, even if the assertion passes. This worked fine in nightwatch-cucumber, so I feel like we're not using it wrong.

Error:

```
√ Passed [equal]: pg-index == pg-index
    ✖ failed
      Error: function timed out, ensure the promise resolves within 60000 milliseconds
          at Timeout._time.default.setTimeout [as _onTimeout] (/Users/rob/git/nightwatch-api/packages/cucumber-example/node_modules/cucumber/lib/user_code_runner.js:81:20)
          at ontimeout (timers.js:436:11)
          at tryOnTimeout (timers.js:300:5)
          at listOnTimeout (timers.js:263:5)
          at Timer.processTimers (timers.js:223:10)
```

## Expected Behavior

Should resolve the promise

## Current Behavior

Times out.

## Possible Solution

Not sure! Is this a bug here or in Nightwatch?

## Steps to Reproduce (for bugs)

See code example above.

## Context

Trying to upgrade existing tests to nightwatch-api

## Your Environment

- Version used: latest (2.2.0)
- Browser Name and version: Chrome headless
- Operating System and version (desktop or mobile): MacOS

**Comment by mucsi96** [comment]
Thanks for your feedback! I was able to reproduce the issue, but I looks the the issue is with the code itself.
You should not do assertions in the callback functions due to not proper error handling in there. Instead you need to do the following:
```
let value;
await client.getAttribute('body', 'id', result => value = result.value );
await client.assert.equal(value, 'pg-index');
```

**Comment by mucsi96** [comment]
Will try to highlight this in the docs

**Comment by rgeraldporter** [comment]
Thanks. A bit ugly when you're doing functional programming style but working is better than not working! I'll give this a try and close if it works.

**Comment by rgeraldporter** [comment]
This works, though does seem to require async/await. I could not find a way for it to work at all in a Promise chain.

**Comment by mucsi96** [comment]
Let,s leave this open until its not clarified in the docs

**Comment by rgeraldporter** [comment]
And thank you for this new interface between Cucumber & Nightwatch. It seems to be working well and has allowed me to remove some cruft out of our scripts. It feels much cleaner than `nightwatch-cucumber` was, now that we're over to it.
