### ISSUE TITLE
Wrong screenshot is being attached when executing in parallel

### ISSUE THREAD

**Issue by inavac182** [mucsi96/nightwatch-api#510]
Hello guys, I think we have an issue that needs your attention. We are running tests using nightwatch-api and cucumber, our tests run in parallel. The issue is in the screenshot we followed the documentation: https://nightwatch-api.netlify.com/cucumber/ but we found this issue:

## Expected Behavior
So, when we are running in parallel and multiple sessions have issues, we expect to have every screenshot attached to the correct failed scenario.

## Current Behavior
Right now there is a variable `const attachedScreenshots = getScreenshots();` to keep track of what screenshot has already being added the problem with this approach is that if we are running in parallel the value of this variable `attachedScreenshots` is not shared between the different sessions.

## Possible Solution
In our case we only generate one screenshot, so we are always attaching the last screenshot to the failed case, but this is not going to work if there are scenarios generating multiple screenshots.

## Steps to Reproduce (for bugs)
1) Run tests, using cucumberjs in parallel
2) The execution needs to generate screenshots, e.g. on failures.
3) Review the attached screenshots in the report.

## Your Environment

cucumber: "^5.1.0"
nightwatch-api: "^2.2.1"
nightwatch: "^1.1.8"

**Comment by mucsi96** [comment]
Hi @inavac182! Thank for you feedback! I have created a new method for this purpose called `getNewScreenshots` which returns the screenshots created after latest call from the current process. With that attaching screenshots to reports can be much more simple and robust.

Please  check the configuration change you need to do after it's released: https://github.com/mucsi96/nightwatch-api/pull/511/files#diff-90d8ab8dc81e4935ab19fc3dbb3cc8a2

**Comment by mucsi96** [comment]
The new `getNewScreenshots` function is released as part of 2.3.0. https://github.com/mucsi96/nightwatch-api/releases/tag/v2.3.0
