### ISSUE TITLE
Cucumber example timing out

### ISSUE THREAD

**Issue by sergeisomething** [mucsi96/nightwatch-api#52]
With the latest version of nightwatch(1.0.14) cucumber execution doesn't start(which seems like a broken connectivity between the driver and the client). Can reproduce this issue with cucumber-example. I was wondering if there is a problem in my local setup or if there is an issue with the library? Thanks.

**Comment by spnraju** [comment]
Hi @sergeisomething , thank you for the feedback. This has been already noticed with versions later than 1.0.11. We are trying to identify the route cause.

**Comment by sergeisomething** [comment]
Cool! That's what I thought since I saw 49 isn't merged. Please keep us updated

**Comment by light24bulbs** [comment]
This is happening for me as well.  The promise from nightwatch-api never seems to resolve

**Comment by spnraju** [comment]
Hi @sergeisomething , @mucsi96 have fixed the issue and released a new version 2.0.0. Please check with this and let us know. Closing this for now.

**Comment by sergeisomething** [comment]
@spnraju thanks! I can confirm it was resolved. 🥇
