### ISSUE TITLE
No nightwatch commands resolve their promises

### ISSUE THREAD

**Issue by light24bulbs** [mucsi96/nightwatch-api#53]
Trying to determine if this is just my setup or not, but none of the nightwatch api commands inside of cucumber blocks seem to resolve their promises.  Nightwatch will manipulate the page and print to the console, but it will not resolve.  

Nightwatch version 1.0.1 to 1.0.14
nightwatch-api version 1.0.0

A test like this:
```
client.waitForElementVisible('#HeaderApp', 5000).then(() => console.log('FINISHED'))
```
Will output
```
✔ Element <#HeaderApp> was visible after 52 milliseconds.
```
But the promise will not resolve.  

Has anyone else seen this?

**Comment by spnraju** [comment]
Hi @light24bulbs , @mucsi96 have fixed the issue and released a new version. Please check with this and let us know. Closing this for now.

**Comment by light24bulbs** [comment]
Fixed! thank you
