### ISSUE TITLE
How to pass cucumber argument similar to previous nightwatch-cucumber api

### ISSUE THREAD

**Issue by ranjprashant** [mucsi96/nightwatch-api#543]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior

require("nightwatch-cucumber")({
  cucumberArgs: [
    "--compiler",
    "js:babel-core/register",
    "--require",
    "tests/StepDefs/hooks.js",
    "--require",
    "tests/StepDefs",
    "--format",
    "node_modules/cucumber-pretty",
    "--format",
    "json:reports/cucumber.json",
    "tests/features"
  ]
});

currently no option to pass these arguments. 

## Steps to Reproduce (for bugs)

1. 2. 3. 4.

## Your Environment

- Version used:
- Browser Name and version:
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by expphchen** [comment]
Nightwatch API is no longer use the **nightwatch-cucumber runner**.
Please see example : https://github.com/mucsi96/nightwatch-api/tree/master/packages/cucumber-example, It use cucumberjs runner. 

What we did to achieve this was to create a file call cucumber.js and and in the package.json we have script call "test":"cucumber-js "
Example content of the cucumber.js

`let defaultRequirements = [
    '--require-module babel-core/register',
    '--require cucumber.conf.js',
    '--require features/',
    '--format json:reports/cucumber.json',
    '--format node_modules/cucumber-pretty',
    `--tags '@myTest'`
];

defaultRequirements = defaultRequirements.join(' ');

module.exports = {
    default: defaultRequirements
};`

**Comment by mucsi96** [comment]
Thanks for explaining this. Also I like how you use the CucumberJs default profile https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#profiles

I might update the cucumber example to follow this practice. Never liked the long list of flags in package.json

Closing the issue

**Comment by ranjprashant** [comment]
Works perfectly for me.
