### ISSUE TITLE
cucumber.json report can't be produced when a test fails

### ISSUE THREAD

**Issue by marge2312** [mucsi96/nightwatch-api#58]
Hej all!

With the new version of the nightwatch-api i encounter the following problem:
whenever a test of my test set fails the remaining tests are aborted because of the following problem: _Unable to parse cucumberjs output into json_
Anybody else having the same problem? Or any tipps?

(i run nightwatch 1.0.11 cause with 1.0.14 my promises don't resolve...)

best greetings

**Comment by mucsi96** [comment]
Hi @marge2312! Thank for your feedback. Unfortunately this information is not sufficient to start any kind of investigation. Can you provide a minimal project setup where we can reproduce the issue? Also please update every dependency to latest. The latest version of this package no longer supportd Nightwatch 1.0.11

**Comment by marge2312** [comment]
found the evil bug in my setup.js...
sry for bothering u.
wish u all the best and keep up the great work!
