### ISSUE TITLE
How can i integrate nightwatch-video-recorder with nightwatch-api and cucumber, nightwatch-cucumber-reporter? Kindly help

### ISSUE THREAD

**Issue by gnaneswarreddy** [mucsi96/nightwatch-api#597]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Steps to Reproduce (for bugs)

1. 2. 3. 4.

## Your Environment

- Version used:
- Browser Name and version:
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by gnaneswarreddy** [comment]
Can any one let me know how the video recording can be integrated to nightwatch api + cucumber?

**Comment by mucsi96** [comment]
Thanks for submitting the issue. Unfortunately you cannot use any nightwatch plugins with this package as most plugins rely on Nightwatch runner whis is disabled when using this package. My recommendation is to check how nightwatch-video-recorded is done and adjust your cucumber configuration accordingly. Would be great if there would be a webdriver video recorder package independent from Nightwatch itself. I would appreciate to receive a pull request from you with an example to make this part of the docs as am I sure it would be useful for others. Closing this for now.

**Comment by expphchen** [comment]
@gnaneswarreddy I am interested on how to do it as well. I am putting the debug point on the code seeing I am not able to read the browser.capabilities. thought?
```browser.capabilities = undefined
browser.options.videos = undefined
caps.browserName = undefined
caps.deviceName = undefined
caps.platform = undefined
caps.platformName = undefined
caps.platformVersion = undefined
options = undefined
options.enabled = undefined
options.ext = undefined```

**Comment by expphchen** [comment]
> Thanks for submitting the issue. Unfortunately you cannot use any nightwatch plugins with this package as most plugins rely on Nightwatch runner whis is disabled when using this package. My recommendation is to check how nightwatch-video-recorded is done and adjust your cucumber configuration accordingly. Would be great if there would be a webdriver video recorder package independent from Nightwatch itself. I would appreciate to receive a pull request from you with an example to make this part of the docs as am I sure it would be useful for others. Closing this for now.

hi @mucsi96 would you give a bit more pointer on how to access the browser.options from nightwatch-api? or other way of access please? Thanks!
