### ISSUE TITLE
nightwatch-cucumber to nightwatch-api migration help

### ISSUE THREAD

**Issue by BaswaS** [mucsi96/nightwatch-api#60]
Hi I am trying to migrate to nightwatch-api. I have written multiple tests using  nightwatch-cucumber

It would be good if someone can provide an example of migration itself.

**Comment by mucsi96** [comment]
@BaswaS I am working on a migration guide. Hope I can finish it this week.

**Comment by BaswaS** [comment]
thank you and thanks for the nightwatch-cucumber/nightwatch-api

**Comment by BaswaS** [comment]
Hi @mucsi96 ,

Any update on this?

Thanks,

**Comment by spnraju** [comment]
Hi @BaswaS , Please check https://nightwatch-api.netlify.com/cucumber/.
