### ISSUE TITLE
selenium server is hanging and client unable to  connect using selenium cucumber example

### ISSUE THREAD

**Issue by BaswaS** [mucsi96/nightwatch-api#61]
Hi I am trying to migrate to nightwatch-api from nightwatch-cucumber. I tried the setup same as selenium-cucumber example. When I do "npm run test" it's starting the selenium server and waits there forever. seems like the connection between client and selenium is not happening
I am using the latest version of nightwatch-api too

## Expected Behavior
able to establish connection between selenium server and client

## Current Behavior

selenium server starts and hangs there forever

## Your Environment
My setup file:

const {
  setDefaultTimeout, BeforeAll, AfterAll
} = require('cucumber');

const {
  startWebDriver, client, createSession, closeSession
} = require('nightwatch-api');

let launchUrl;
const env = 'default';
setDefaultTimeout(60000);

startWebDriver(env).catch(err => console.error(err));

BeforeAll(async () => {
  setTimeout(() => {
  }, 5000);
  await createSession({ env: process.env.env });
  launchUrl = 'www.google.com';
  client.maximizeWindow();
  return client.init(launchUrl);
});

AfterAll(async () => {
  await closeSession();
});
- Version used:
- Browser Name and version:
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by mucsi96** [comment]
Hi @BaswaS! Thanks for your feedback. I just tried to run the `cucumber-selenium-example` example. It runs perfectly for me. The only thing you should know that there are two npm scripts.
- `npm run test:setup` You should run this first in one terminal. This will not show anything in the log. This is simulating your express node.js application you are testing. Currently it's running the selenium server.
- `npm run test:run` You can run this after the "application" (in this case the `npm run test:setup`) started. This is doing the actual testing. This is running the CucumberJs and establishes connection with selenium.

Also I noticed many mistakes in you code. Looks like you are not familiar with callbacks and asynchronous nature of JavaScript. You should definitely improve on that if you want to do integration testing in JavaScript.
```
BeforeAll(async () => {
  setTimeout(() => {}, 5000); // <--- what is this for? This is not blocking the execution for 5s as you think
  await createSession({ env: process.env.env });
  launchUrl = 'www.google.com'; // <- this is not a valid url. You shoud start with `https://`
  client.maximizeWindow(); // <-- this is an asynchronous operation. You should await it before moving to the next command
  return client.init(launchUrl); // <- same here. No need to return. Just await it.
});
```

So you need this. I have tried to run this as well. It was running without any issues.
```
BeforeAll(async () => {
  await new Promise(resolve => setTimeout(resolve, 5000));
  await createSession({ env: process.env.env });
  launchUrl = 'https://www.google.com';
  await client.maximizeWindow();
  await client.init(launchUrl);
});
```

Hope this helps. Closing the issue for now.
