### ISSUE TITLE
 TypeError [ERR_UNESCAPED_CHARACTERS]:  When 'browserstack.selenium_version':'3.14.0' is specified in desiredCapabilities

### ISSUE THREAD

**Issue by sanjapa** [mucsi96/nightwatch-api#623]
Test can not be executed ,If I want to specify the  **'browserstack.selenium_version' :'3.14.0'** property in desiredCapabilities. The following error is returned: 

```
Error while running .isElementDisplayed() protocol action: TypeError [ERR_UNESCAPED_CHARACTERS]: Er
ror while trying to create HTTP request for "/wd/hub/session/edc11014c2d603cf4bd512b8368ebcb48502712
f/element/[object Object]/displayed": Request path contains unescaped characters
    at new ClientRequest (_http_client.js:115:13)
    at Object.request (http.js:42:10)
    at HttpRequest.createHttpRequest (\nightwatch\node_modules\nightwatch\
lib\http\request.js:112:55)
    at HttpRequest.send (\nightwatch\node_modules\nightwatch\lib\http\requ
est.js:191:29)
    at Promise (\nightwatch\node_modules\nightwatch\lib\transport\transpor
t.js:189:15)
    at new Promise (<anonymous>)
    at Selenium2Protocol.sendProtocolAction (\nightwatch\node_modules\nigh
twatch\lib\transport\transport.js:187:12)
    at Selenium2Protocol.runProtocolAction (\nightwatch\node_modules\night
watch\lib\transport\jsonwire.js:61:17)
    at Object.isElementDisplayed (\nightwatch\node_modules\nightwatch\lib\
transport\actions.js:54:10)
    at Selenium2Protocol.executeProtocolAction (\nightwatch\node_modules\n
ightwatch\lib\transport\transport.js:235:48)
    at WaitForElementVisible.executeProtocolAction (\nightwatch\node_modul
es\nightwatch\lib\element\command.js:201:27)
    at WaitForElementVisible.protocolAction (\nightwatch\node_modules\nigh
twatch\lib\api\element-commands\_waitForDisplayed.js:5:17)
    at WaitForElementVisible.elementFound (\nightwatch\node_modules\nightw
atch\lib\element\command.js:168:17)
    at action (\nightwatch\node_modules\nightwatch\lib\api\element-command
s\_waitForDisplayed.js:40:36)
    at PeriodicPromise.perform (\nightwatch\node_modules\nightwatch\lib\ut
il\periodic-promise.js:79:29)
    at PeriodicPromise.runAction (nightwatch\node_modules\nightwatch\lib\
util\periodic-promise.js:48:33)
```

The error won't appear if I specify other version like 2.53.0 'browserstack.selenium_version' :'2.53.0'

nightwatch-api version: 2.3.0
nightwatch- version: 1.1.12
chrome driver version:75.0.0

**Here is my config file**
const chromedriver = require('chromedriver');
const seleniumServer = require('selenium-server');
module.exports = {
    'custom_commands_path':
        [
            "./commands/",
            "./commands/Api",
        ],
    'custom_assertions_path': '',
    'page_objects_path': 'page-objects',
    'globals_path': 'globals/globals.js',
    'end_session_on_fail': false,
    'skip_testcases_on_fail': false,
    test_settings: {
        default: {
            'persist_globals': true,
            selenium: {
                start_process: false,
                host: 'hub-cloud.browserstack.com',
                port: 80
            },
            desiredCapabilities: {
                'browserstack.user': 'XXX',
                'browserstack.key': 'XXX',
                os: 'Windows',
                os_version: '10',
                resolution: '1280x1024',
                'browserstack.selenium_version': '3.14.0'
            }
        },
        chrome: {
            desiredCapabilities: {
                browserName: 'chrome',
                javascriptEnabled: true,
                acceptSslCerts: true,
                chromeOptions: {
                    args: ['disable-gpu', '--start-maximized']
                }
            }
        },
        chromeHeadless: {
            desiredCapabilities: {
                browserName: 'chrome',
                javascriptEnabled: true,
                acceptSslCerts: true,
                chromeOptions: {
                    args: ['disable-gpu', '--start-maximized', '--headless', 'window-size=1920,1080']
                }
            }
        },
        firefox: {
            desiredCapabilities: {
                browserName: 'firefox',
                javascriptEnabled: true,
                acceptSslCerts: true,
                marionette: true
            }
        },
        localChrome: {
            'persist_globals': true,
            selenium: {
                start_process: true,
                host: '127.0.0.1',
                port: 4444,
                server_path: seleniumServer.path,
            },
            screenshots: {
                enabled: true,
                path: "screenshots"
            },
            desiredCapabilities: {
                server_path: chromedriver.path,
                browserName: 'chrome',
                javascriptEnabled: true,
                acceptSslCerts: true,
                chromeOptions: {
                    args: ['disable-gpu', '--start-maximized']
                }
            }
        }
    }
};

**Comment by spnraju** [comment]
Hi @sanjapa , Thank you for reporting the issue. But would you mind removing the browserstack creds from the post?

**Comment by spnraju** [comment]
Hi @sanjapa do you have any sample project with this config on github? It would be helpful in investigating it.

**Comment by sanjapa** [comment]
Hi @spnraju here is a link of a sample project I've just created using the config https://github.com/sanjapa/testExample

**Comment by spnraju** [comment]
Hi @sanjapa , this seem to be an issue with nightwatch itself. They had similar issue before and it is fixed. https://github.com/nightwatchjs/nightwatch/issues/1864. Probably you can raise an issue there as well.

**Comment by sanjapa** [comment]
Hi @spnraju, thank you for the response. Yes, the test are executing fine even if the property is there but with lower selenium version. 
As to why I want to specify the particular version is that on lower selenium version (the default version of Selenium when executing tests on BrowserStack is 2.53.0.) and last version on nightwatch, nightwatch-api and chrome driver, there is another bug which can be skipped when test are run on selenium version 3.14.0 ([https://github.com/mucsi96/nightwatch-api/issues/450]) .

**Comment by spnraju** [comment]
Hi @sanjapa can you try this solution? https://github.com/nightwatchjs/nightwatch/issues/2126#issuecomment-500574399

**Comment by spnraju** [comment]
Closing this as we have a issue opened in nightwatch repo.
