### ISSUE TITLE
[Question] How to show full log for night watch

### ISSUE THREAD

**Issue by thanhgb** [mucsi96/nightwatch-api#627]
I usually get issue ECONNRESET
![image](https://user-images.githubusercontent.com/38931618/60385741-b604bd00-9ab6-11e9-866c-fc8b4ad4d37f.png)

However, I don't understand why it just happen when the code works on a specific page XXX. Before go to page XXX, I visited login page, fill in account/pass,....

So I want to show all the log when nightwatch communicate with chrome browser to figure out which cause issue.

This is my nightwatch.conf
![image](https://user-images.githubusercontent.com/38931618/60385754-11cf4600-9ab7-11e9-8d1c-df7cb98392a0.png)

## Your Environment

- Version used:
    "nightwatch": "^1.1.12",
    "nightwatch-api": "^2.3.0",
   "cucumber": "^5.1.0",
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): MAC

**Comment by spnraju** [comment]
Hey @thanhgb , Thank you for reaching out. But I could not understand your question. What is that you are looking for? Are you talking about verbose logs in nightwatch?

**Comment by spnraju** [comment]
I dont think this will work. Can you please the below? 

https://github.com/mucsi96/nightwatch-api/blob/master/packages/cucumber-example/nightwatch.conf.js#L5

You can probably set this property to true.

Let us know if that solves your problem.

**Comment by thanhgb** [comment]
thanks @spnraju 
it solved my problem :) 
Base on this, I knew why the issue `ECONNRESET` happen
