### ISSUE TITLE
TypeError: this.reporter.saveErrorScreenshot is not a function when test are failing on click command

### ISSUE THREAD

**Issue by ituradastra** [mucsi96/nightwatch-api#628]
This is happening when tests are run on browserStack 
When test are failing with following error : 
```
 Response 500 POST http://hub-cloud.browserstack.com/wd/hub/session/a8e1d411ba3d3a457efa0824134fc
f52640ffd63/element/65/click (348ms)
   { state: 'unhandled error',
...
     element click intercepted: Element is not clickable at point.
}
```
The following type error appear: 
 ```
**TypeError: this.reporter.saveErrorScreenshot is not a function**
       at endReadableNT (_stream_readable.js:1129:12)
       at process._tickCallback (internal/process/next_tick.js:63:19)
```
Versions:
"nightwatch": "^1.1.12",
 "nightwatch-api": "^2.3.0",
Test are executed on chrome browser on version 75 (tried on different version but the same happens).

**Comment by spnraju** [comment]
Hi @sanjapa would you mind sharing some example repo so that I can reproduce this?

**Comment by quantranbr** [comment]
I also face this issue, I use nightwatch-api & cucumberjs
When this issue is happened, the test script is not jump into the After step in cucumber.conf.js

**Comment by spnraju** [comment]
Hi @quantranbr , would you mind sharing some sample code to reporoduce this issue?

**Comment by spnraju** [comment]
Closing this as there is no response.
