### ISSUE TITLE
NightwatAPI configuration with Cucumber

### ISSUE THREAD

**Issue by eternityCoder1** [mucsi96/nightwatch-api#63]
how to pass arguments to cucumber.js in Nightwatch-API package?

in earlier package (nightwatch-cucumber) we used to pass it as below:
require('nightwatch-api')({
cucumberArgs: ['--require', 'hooks.js', '--require', 'timeout.js', '--require', 'step_definitions', '--format',
'json:reports/cucumber.json', 'features'],
nightwatchOutput: false
});
we used to add this line of code in Nightwatch.js configuration file..

I am using with Selenium Server rathar than using webdriver (ie. chrome etc).

Greatly appreciate help.

**Comment by mucsi96** [comment]
With nightwatch-api you run cucumber tests with cucumberjs itself. So you can pass the arguments directly.

**Comment by spnraju** [comment]
@GCArg, https://github.com/mucsi96/nightwatch-api/blob/master/packages/cucumber-selenium-example/package.json might help

**Comment by BaswaS** [comment]
Hi @spnraju,

I tried your the commands just like your example.

"test:setup": "babel-node src/helper/test/server.js",
"test:run": "cucumber-js --require-module babel-core/register --require test/support --require step-definitions --format node_modules/cucumber-pretty",
"test": "start-server-and-test test:setup http-get://localhost:4444/status test:run",


But when i do npm run test, I am getting server closed unexpectedly error as shown below
 npm run test

> xmautomationnightwatch@1.0.0 test C:\source\xm-nightwatch-automation
> start-server-and-test test:setup http-get://localhost:4444/status test:run

starting server using command "npm run test:setup"
and when url "http-get://localhost:4444/status" is responding
running tests using command "test:run"

> xmautomationnightwatch@1.0.0 test:setup C:\source\xm-nightwatch-automation
> babel-node src/helper/test/server.js

Error: server closed unexpectedly
    at ChildProcess.onClose (C:\source\xm-nightwatch-automation\node_modules\start-server-and-test\src\index.js:60:14)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.cp.emit (C:\source\xm-nightwatch-automation\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xmautomationnightwatch@1.0.0 test: `start-server-and-test test:setup http-get://localhost:4444/status test:run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xmautomationnightwatch@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Baswa\AppData\Roaming\npm-cache\_logs\2019-01-17T00_28_07_239Z-debug.log

**Comment by spnraju** [comment]
Hi @BaswaS are you running the example as is? or you have changed something?

**Comment by BaswaS** [comment]
Hi @spnraju ,

No.This is my local project which was originally in nightwatch-cucumber. I am trying to migrate to nightwatch-api

**Comment by BaswaS** [comment]
Hi @spnraju,

I got past the above error. But now when i do npm run test:run cucumber is not finding any scenarios.

Please find my sample project [here](https://github.com/BaswaS/nightwatch-api-sample) . I use page object model in my project which is little bit different from your example. I hope it doesn't make any difference. Feel free to correct me if i miss anything!

Thanks
