### ISSUE TITLE
Unable to doubleClick on elements using nightwatch-api...

### ISSUE THREAD

**Issue by devil-pc** [mucsi96/nightwatch-api#647]
Hello,

I am trying to double click on a table after a search item is returned and the console shows no error - test is green but the double click is not performed. Any ideas?

Here is part of my code:

Then('I click on Search button', async () => {
  await client.click('#myElement')
  await client.waitForElementVisible('#mySearchResult, 2000);
  await client.doubleClick(); - I need to double click here on my search result....
  await client.waitForElementVisible('#someElementToWait');
}

After running the test:

1 scenario (1 passed)
5 steps (5 passed)
0m09.326s

But the double click was not performed.....

I am using latest versions of everything....

**Comment by teajsshekokar** [comment]
Hey @devil-pc 

Double click would be performed on the current position of the mouse pointer. You have to move the mouse pointer over your #mySearchResult. LIke this, see below example

Then('I click on Search button', async () => {
await client.click('#myElement')
await client.waitForElementVisible('#mySearchResult, 2000);
**/********Move mouse pointer over search result*******/
await client.moveToElement('#mySearchResult');**
await client.doubleClick(); - I need to double click here on my search result....
await client.waitForElementVisible('#someElementToWait');
}

**Comment by devil-pc** [comment]
Thank you for the reply - it works. I also managed to double click using the below code:

await client.execute( function() {  
  var targLink = window.document.querySelector("CSS Selector");
  var clickEvent  = document.createEvent ('MouseEvents');
  clickEvent.initEvent ('dblclick', true, true);
  targLink.dispatchEvent (clickEvent);
})
