### ISSUE TITLE
cucumber.json file cant be used for generating report in Afterall hook

### ISSUE THREAD

**Issue by eternityCoder1** [mucsi96/nightwatch-api#73]
I am running my test using cucumberjs runner, in Afterall hook i tried to generate cucumber-html-report using cucumber.json but i am getting error:
Unable to parse cucumberjs output inot json:  'results/cucumber_report.json' SyntexError: results/cucumber_report.json: Unexpected end of JSON input
         at JSON.parse (<anonymous>)
         at Object.readFileSync (C:\otg-uti-automation-newVersion\node_modules\jsonfile\index.js:69:17)

Does this mean cucumberjs not finished writing to cucumber_report.json ?? Because when i try to generate report after the cucumberjs runner finished, it works fine. i put the code to generate report in index.js and runs it after cucumberjs is completed.
in package.json  
"cucumber-js features/*.feature --require step_definitions --require globals.js --format json:results/cucumber_report.json&&node index.js"

**Comment by spnraju** [comment]
This seems to be not possible as per below link.

https://stackoverflow.com/questions/45920217/generate-cucumber-report-after-test-execution-with-nightwatch-cucumber

Closing this issue as it is no way related to this repo.
