### ISSUE TITLE
failure in testcase killing the node process, not able to executed js file to generate cucumber report.

### ISSUE THREAD

**Issue by eternityCoder1** [mucsi96/nightwatch-api#74]
in nightwatch.conf.js  value for abortOnFailure = false
while execution when i am getting failure it says abortOnFailure = true.

Not sure why.

Also it kills process and i am not able to run another node command that i wanted to run another js file to generate cucumber report.

package.json command as below:
cucumber-js features/*.feature --require step_definitions --require globals.js --format json:results/cucumber_report.json&&node index.js

**Comment by spnraju** [comment]
From where did you get this property? I see the below property from documentation. 
http://nightwatchjs.org/gettingstarted#base-settings
end_session_on_fail
--

**Comment by eternityCoder1** [comment]
![2019-01-09_21-34-30](https://user-images.githubusercontent.com/46330052/50942458-c9fc2a00-1456-11e9-8229-a287b63c05be.png)

**Comment by eternityCoder1** [comment]
![2019-01-09_21-38-31](https://user-images.githubusercontent.com/46330052/50942590-2c552a80-1457-11e9-9244-f28b09e4b6b8.png)

**Comment by eternityCoder1** [comment]
any update on this?

**Comment by spnraju** [comment]
@eternityCoder1 we will need more details. Also, request you to try this property with pure nightwatchjs. 

> cucumber-js features/*.feature --require step_definitions --require globals.js --format json:results/cucumber_report.json&&node index.js

As far as I know, this will not work. You might get some help if you redirect this question to cucumberjs repo.

**Comment by mucsi96** [comment]
Unfortunatly report generation must be in a separate process. Check the “HTML reports” section of  nightwatch-cucumber project

**Comment by spnraju** [comment]
> @mucsi96 i believe it is very difficult to generate report in another process particularly in the case of failure in test. It kills the process.

I have been doing this for a while in one of my projects. A json file will be generated by cucumber with details irrespective of passed or failed status. You can use this json to generate html reports through some good libraries.
