### ISSUE TITLE
Error: An error occurred while trying to start the Nightwatch Runner: Unsupported browser: microsoftedge. There is no available driver.

### ISSUE THREAD

**Issue by PradeepKumarTyagi** [mucsi96/nightwatch-api#766]
Using Nightwatch 1.1.13 to automate app on Microsoft Edge on Mac OS High Sierra but getting following error:
Error: An error occurred while trying to start the Nightwatch Runner: Unsupported browser: microsoftedge. There is no available driver.

## Expected Behavior

No Error

## Current Behavior

Error: An error occurred while trying to start the Nightwatch Runner: Unsupported browser: microsoftedge. There is no available driver.

**Comment by spnraju** [comment]
Hi @PradeepKumarTyagi  Please refer to https://github.com/mucsi96/nightwatch-api/issues/767#issuecomment-517329841.
