### ISSUE TITLE
Error: An error occurred while trying to start the Nightwatch Runner: Unsupported browser: microsoftedge. There is no available driver.

### ISSUE THREAD

**Issue by harshsinghania** [mucsi96/nightwatch-api#767]
Error: An error occurred while trying to start the Nightwatch Runner: Unsupported browser: microsoftedge. There is no available driver.

Trying to  automate app on macos using Nightwatch but getting below error:
Error: An error occurred while trying to start the Nightwatch Runner: Unsupported browser: microsoftedge. There is no available driver.

**Comment by spnraju** [comment]
Hi @harshsinghania ,Thank you for bringing this to our notice. if this is an issue with nightwatch itself, you may have to raise it in the respective repo. The details provided in this issue are not enough to understand the issue. Please try to add more details like config or logs when you raise issues in future. 

You may refer to https://github.com/mucsi96/nightwatch-api/issues/18 for some info on nightwatch support for edge.
