### ISSUE TITLE
Any tips on displaying scenario outline "example table" in the json result?

### ISSUE THREAD

**Issue by expphchen** [mucsi96/nightwatch-api#79]
## Current Behavior
The cucumber.json that was produced does not contain data from scenario outline

## Possible Solution
Found some other people wrote the plugin on ruby, https://github.com/cucumber/cucumber-ruby/pull/700/files, could not find the JS version. Anyone out there using the framework facing the same? Any thought?

**Comment by spnraju** [comment]
Hi @expphchen your question should have been to cucumberjs repo. This is something out of scope for this repo. Closing this issue for now.
