### ISSUE TITLE
Test workers and parallel launch

### ISSUE THREAD

**Issue by Tarvald** [mucsi96/nightwatch-api#796]
Hi,

Does test_workers option works in nightwatch-api?

It is working perfectly in Nightwatch however when I set this for nightwach-api it didn't do anything.

Best regards

**Comment by spnraju** [comment]
Hi @Tarvald , Please note that that option will not have any impact on nightwatch-api. Please refer to below links. 

https://github.com/mucsi96/nightwatch-api/issues/426#issuecomment-485269667
https://github.com/mucsi96/nightwatch-api/issues/247

**Comment by marge2312** [comment]
I have the same issue.
I used nightwach-cucumber before and now since using nightwatch-api test_workers does not work anymore. can u pls dig into that a little bit? i did not change anything else. just upgraded to nightwatch-api

**Comment by spnraju** [comment]
Hello @marge2312 , would you mind looking at the links provided in the comment above.

**Comment by marge2312** [comment]
i did and unfortunately it didn't work for me

**Comment by spnraju** [comment]
Maybe you are doing something wrong or there is an issue with cucumber. Please get in touch with cucumber js team if you feel the issue is with cucumber.
