### ISSUE TITLE
New instance of Chrome browser in incognito mode still remembers HttpOnly cookies

### ISSUE THREAD

**Issue by Qvatra** [mucsi96/nightwatch-api#811]
On my website I started to use HttpOnly cookies for session persistence after refresh.

The problem is that tests are started to fail simply because after first login browser still sees cookie and login steps for the next test fail.

Nightwatch api provides deleteCookies method but it can not delete HttpOnly cookies.

I tried to configure chrome to run in incognito mode but it still remembers the cookie during test run.
When I was testing manually in incognito mode it was working ok as long as i close browser after each test, so my assumption is that Nightwatch doesn't actually closes the browser instance and as a result browser remembers cookie.

is this can be considered a bug or I'm missing something?
Thank you in advance.

**Comment by Qvatra** [comment]
I found a way but not sure that this is the right way:
```
const { createSession, closeSession } = require('nightwatch-api')
const nightwatchConfigPath = 'e2e/nightwatch.conf.js'

Before(async () => {
  await createSession({
    configFile: nightwatchConfigPath
  })
})

After(async ({ result: { status } }) => {
  await closeSession()
})
```

**Comment by Qvatra** [comment]
update: noticed that test are working even without 'incognito' setting for browser

**Comment by spnraju** [comment]
Hello @Qvatra , thank you for bringing this to our notice. I am afraid this is not an issue with nightwatch-api. but with nightwatchjs https://nightwatchjs.org/api/commands/#deleteCookies. Please report it [here](https://github.com/nightwatchjs/nightwatch/issues)
