### ISSUE TITLE
getting error while trying run with tags

### ISSUE THREAD

**Issue by satheesh6789** [mucsi96/nightwatch-api#814]
npm run test:cucumber -- --tag Seleniumeasy

> automation@1.0.0 test:cucumber C:\Users\****\Desktop\Automation
> mkdirp report && cucumber-js --require cucumber.conf.js --require step-definitions --format node_modules/cucumber-pretty --format json:report/cucumber_report.json "--tag" "Seleniumeasy"

error: unknown option `--tag'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! automation@1.0.0 test:cucumber: `mkdirp report && cucumber-js --require cucumber.conf.js --require step-definitions --format node_modules/cucumber-pretty --format json:report/cucumber_report.json "--tag" "Seleniumeasy"`
npm ERR! Exit status 1

please let me know what are the changes i need to config file , help me to fix this issue.

upload an example with the @tag in feature and changes in config files. Thanks for the help!

**Comment by spnraju** [comment]
Hi @satheesh6789, I suggest you to please go through the relative documentation before raising issues here. 

`npm run test:cucumber -- --tags "@Seleniumeasy" ` should work.

Documentation here. https://cucumber.io/docs/cucumber/api/#tag-expressions
