### ISSUE TITLE
[QUESTION] Is there a way to start two sessions and control it from the test?

### ISSUE THREAD

**Issue by segrey11** [mucsi96/nightwatch-api#815]
Hi. I have to test a webrtc phone. In order to do so, I need to open two browsers with different users make them interact with each other. Currently, I use the approach described in 
[https://github.com/beatfactor/nightwatch-webrtcdemo](https://github.com/beatfactor/nightwatch-webrtcdemo) when I start Nightwatch with 2 envs:

`--env chrome, chrome` and use environment variables `chrome_1` and `chrome_2` to tell Nightwatch what each process should do.

This is not convenient because each client does not know anything about the other side and I need to have some external storage to share different data across the browsers. Further, this approach has a reporting issue, I have two report files for each Nightwatch process which is not easy to read.

The question is there any way to create two sessions and control them from test? Something like: 

```
Then(/^I  establish a call between "(.*?)" and  "(.*?)" $/, async (number1, number2) => {
    await client1.call(number2)
    await client2.answer(number1)
});
```

**Comment by spnraju** [comment]
I think this is something not possible at the moment. Closing it for now.
