### ISSUE TITLE
Parallel run separates scenarios but not feature 

### ISSUE THREAD

**Issue by saladinProcrastinator** [mucsi96/nightwatch-api#822]
## Expected Behavior

Need to paralyze feature files

## Current Behavior

Scenarios paralyzing in Chrome.
Works fine with Firefox

## Steps to Reproduce (for bugs)

    "test": "mkdirp report && cucumber-js features/**/*.feature --require cucumber.conf.js --require-module @babel/register --require step-definitions --parallel 2 --format node_modules/cucumber-pretty --format json:report/cucumber_report.json",

## Your Environment

Window 10
Linux 16.04
node v12.13.0

**Comment by spnraju** [comment]
Hi @saladinProcrastinator Could you please add more details? I am sorry but I am not able to understand what you are looking for.

**Comment by saladinProcrastinator** [comment]
Hi @spnraju !

I mean when I run tests in parallel mode then paralleled by scenarios in feature but not by feature files.
To reproduce it you also can use your repository
https://github.com/mucsi96/nightwatch-api/tree/master/packages/cucumber-example

**Comment by spnraju** [comment]
Hey @saladinProcrastinator thank you for the details. I am afraid this is a limitation on cucumberjs itself. As per the documentation https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#parallel-experimental, only scenarios can be run in parallel. Hope that helps.
