### ISSUE TITLE
Error: read ECONNRESET after close browser in parallel run

### ISSUE THREAD

**Issue by saladinProcrastinator** [mucsi96/nightwatch-api#823]
ERROR after browser closing in parallel mode after closing the first one.
    DELETE  /wd/hub/session/37ed4e6afe84c9f8a2a548bcdd5d7171 - ECONNRESET
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
 Error while running .sessionAction() protocol action: An unknown error has occurred.

![500](https://user-images.githubusercontent.com/57943849/69721712-1eb39c80-111e-11ea-8f11-a1610232a6a4.jpg)

Env:
Chrome 78.0.3904.108 (Official Build) (64-bit)
Firefox 70.0.1 (64-bit)

Windows 10
Linux 16.04
node v12.13.0

**Comment by spnraju** [comment]
Hi @saladinProcrastinator , thank you for reporting this. But it would be great if you can provide us a sample repo where we can reproduce this. Also, Kindly help by sharing your config and other details which will help us in investigating this.

**Comment by saladinProcrastinator** [comment]
Hi @spnraju 
sure
https://github.com/mucsi96/nightwatch-api/tree/master/packages/cucumber-example

    "test": "mkdirp report && cucumber-js --parallel 2 --require-module @babel/register --require cucumber.conf.js --require step-definitions --format node_modules/cucumber-pretty --format json:report/cucumber_report.json",

**Comment by spnraju** [comment]
Hi @saladinProcrastinator . thank you for the details. we are investigating the issue and will revert once we find somthing useful. You may want to take a look at below items just in case if they help. 

https://github.com/cucumber/cucumber-js/issues/1231
https://github.com/simondean/parallel-cucumber-js

**Comment by spnraju** [comment]
Closing this as there is no other activity and a script is added to run parallel features inside selenium example.

**Comment by ranjprashant** [comment]
Getting error on executing cucumber in parallel. Almost every alternate execution. 
**DELETE  /wd/hub/session/4d61c52b-4e56-4a1e-93dc-2184708e897f - ECONNRESET
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
 Error while running .sessionAction() protocol action: Error ECONNRESET: read ECONNRESET**
