### ISSUE TITLE
Stuck after callback return

### ISSUE THREAD

**Issue by HariBhandari07** [mucsi96/nightwatch-api#824]
![Screenshot from 2019-11-29 14-31-21](https://user-images.githubusercontent.com/34328907/69856115-fb6f2580-12b4-11ea-9fa7-0e34981fd2dc.png)
Callback stucks after return statement.
- Version used: nightwatch-api: 3.0.1 and nightwatch: 1.3.0
- Browser Name and version: Chrome 74.0.3729.169
- Operating System and version (desktop or mobile): Ubuntu 18.04
- Link to your project:

Here's a sample code:
```
const { client } = require('nightwatch-api');

module.exports = {
    url() {
        return this.api.launch_url;
    },
    commands: {
        createNewMasterKey(masterPassword) {
            return this.waitForElementVisible('@newButton').api.element('@newButton', function(result) {
                return this.elementIdClick(result.value.ELEMENT);
            });
        }
    },
    elements: {
        newButton: {
            selector: '//i[@class="fa fa-plus open__icon-i"]',
            locateStrategy: 'xpath'
        }
    }
};
```

**Comment by spnraju** [comment]
Hey @HariBhandari07 . thanks for reporting this. can you try to upgrade nightwatch to 1.3.1 and let us know? https://github.com/nightwatchjs/nightwatch/releases/tag/v1.3.1

**Comment by HariBhandari07** [comment]
Same issue with 1.3.1

**Comment by spnraju** [comment]
Hi @HariBhandari07 Would you be able to provide any sample code where we will be able to reproduce this issue?

**Comment by spnraju** [comment]
Closing this as there was no response.
