### ISSUE TITLE
Any way to get the success log?

### ISSUE THREAD

**Issue by which-ouer** [mucsi96/nightwatch-api#827]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Steps to Reproduce (for bugs)

1. 2. 3. 4.

## Context

Any way to get the Nightwatch success logs like "√ Element <body> was visible after 96 milliseconds."?

## Your Environment

- Version used: 3.0.1
- Browser Name and version: chrome v77
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by spnraju** [comment]
Please add more details if the issue still exists.
