### ISSUE TITLE
Unable to run multibrowser in parallel as each time same browser gets opened

### ISSUE THREAD

**Issue by paraspandiyar** [mucsi96/nightwatch-api#828]
package .json command

"scripts": {
    "e2e-test":mkdirp report && cucumber-js --tags @${TAG=automationInProgress} --parallel 2 --require-module @babel/register --require ./cucumber.conf.js --require ./tests/system/step-definitions --format ./node_modules/cucumber-pretty --format json:report/cucumber_report.json

cucumber.conf.js
 I was trying to specify both browsers in env of startwebsdriver method as global hooks

Also tried specifying -e or env in package .json script command but each time it says an (This used to work fine in nightwatch <1 )

error: unknown option '-e'

Before(async () => {
    await startWebDriver({env: chrome},{env: firefox})
    await createSession()
})

**When i try to run the script it launches two same browsers either chrome or firefox depending upon the sequence it is mentioned . I am trying to launch one browser of chrome and one of firefox with same command**

**Comment by spnraju** [comment]
Yes. This is a limitation on the core nightwatch package. We will check if this is changed in core package.
