### ISSUE TITLE
Nightwatch API TS Definition

### ISSUE THREAD

**Issue by jleck** [mucsi96/nightwatch-api#833]
Hi,

I've just been trying to use the module within my typescript project, but the following lline from index.d.ts errors:

```ts
import { Api } from 'nightwatch';
```

I can fix this by changing it to:

```ts
import { NightwatchAPI as Api } from 'nightwatch';
```

I did however look at your tsconfig, and note you load in your own type definitions. Might to be useful to document the need for setting `typeRoots` somewhere.

**Comment by mucsi96** [comment]
Hi. Thanks for submitting the issue. Unfortunately I was expecting this issue. I will take a look what can I do

**Comment by christophedebatz** [comment]
Same issue currently with the last version.. :-(

**Comment by jleck** [comment]
Hi @christophedebatz, if you add the types within this package as well as the standard types, it should work as is.

**Comment by christophedebatz** [comment]
When you say "within this package", do you mean that I have to manually modify some file of my node_modules or another file I don't know about ? Thanks @jleck

**Comment by jleck** [comment]
HI @christophedebatz ,

In your tsconfig.json, add:

```json
{
    "compilerOptions": {
        "typeRoots": [
            "./node_modules/nightwatch-api/types",
            "./node_modules/@types"
        ]
    }
}
```

That will make it pick up the modified type definitions from this package. While I think it should be refactored so this isn't needed, it does work for now.

**Comment by christophedebatz** [comment]
Thanks @jleck but it produced some compilations errors :(

Here is my `src/features/google.ts` test file
```
import { client } from 'nightwatch-api';
import { Given, Then } from 'cucumber';

Given(/^I open Google's search page$/, () => {
  return client.url('http://google.com').waitForElementVisible('body', 1000);
});

Then(/^the title is "([^"]*)"$/, title => {
  return client.assert.title(title);
});

Then(/^the Google search form exists$/, () => {
  return client.assert.visible('input[name="q"]');
});
```

My `src/features/google.feature` cucumber file:
```
Feature: Google Search

Scenario: Searching Google

  Given I open Google's search page
  Then the title is "Google"
  And the Google search form exists
```

And finally my gulpfile which make two things:
- Compile my ts into es5 js according to my `tsconfig.jon`
- Launch the tests with the nightwatch-api given command

My `gulpfile.js`:
```
const compile = () => {
  const tsProject = ts.createProject('./tsconfig.json');
  return gulp.src('src/**/*.ts')
      .pipe(tsProject())
      .js.pipe(gulp.dest('build'))
      .pipe(gulp.src('src/**/*.feature')
      .pipe(gulp.dest('build')))
      .on('error', console.log);
}

const run = () => {
  return shell.task(`cucumber-js 
    --require cucumber.conf.js 
    --require step-definitions 
    --format node_modules/cucumber-pretty
    build/features
    `);
  }
gulp.task('compile', compile);
gulp.task('default', gulp.series(compile, run));
```

The error:
```
[12:00:03] Using gulpfile ~/workspace/hozana/qa-validation/gulpfile.js
[12:00:03] Starting 'default'...
[12:00:03] Starting 'compile'...
src/features/hozana.org/google.ts(5,17): error TS2349: This expression is not callable.
  No constituent of type 'string | Function | Promise<Api> | Expect | Sections | Pages' is callable.
src/features/hozana.org/google.ts(9,24): error TS2339: Property 'title' does not exist on type 'string | Function | Promise<Api> | Expect | Sections | Pages'.
  Property 'title' does not exist on type 'string'.
src/features/hozana.org/google.ts(13,24): error TS2339: Property 'visible' does not exist on type 'string | Function | Promise<Api> | Expect | Sections | Pages'.
  Property 'visible' does not exist on type 'string'.
TypeScript: 3 semantic errors
TypeScript: emit succeeded (with errors)
[12:00:05] 'compile' errored after 2.49 s
[12:00:05] Error: TypeScript: Compilation failed
```

Do you have any idea?
Here the error is just compilation error.

**Comment by christophedebatz** [comment]
Thanks @jleck 
Do you had any other issues with the typings? For me yes, just take a look here:
My code, very simple:
```
import { client } from 'nightwatch-api'
import { Given } from 'cucumber'

Given('I go to hozana.org', () => {
  return client.assert.visible('input[name=jumbotron]')
})
```
And TS error:
```
src/features/homepage.ts:6:24 - error TS2339: Property 'visible' does not exist on type 'string | Function | Promise<Api> | Expect | Sections | Pages'.
  Property 'visible' does not exist on type 'string'.

6   return client.assert.visible('input[name=jumbotron]')
```

Any idea?

**Comment by jleck** [comment]
Hi @christophedebatz ,

I'm using `.waitForElementVisible('input[name=jumbotron]')` without issue, does that work for you?

P.S. I'm using this with cucumber too!

**Comment by jleck** [comment]
@christophedebatz actually just noticed, I'm always using through a page object too.

**Comment by christophedebatz** [comment]
Hello @jleck thank you for replying quickly,
Can you send me your conifgurations files please (tsc, cucumber and nightwatch), because I'm still encountering some types errors and the page object does not work with Typescript for me. 
Thanks a lot,

**Comment by christophedebatz** [comment]
@jleck 
Le `waitForElementVisible` is working for me but all the  `client.assert.XXXX` is not recognized by typescript linter? And you?

**Comment by jleck** [comment]
@christophedebatz sorry for the delay, just seen this.

I don't seem to have any TS after loading those types. Although IMO I would use any for now, as the types don't really match what's actually available.
