### ISSUE TITLE
The same error is shown 6 times

### ISSUE THREAD

**Issue by azinchenko91** [mucsi96/nightwatch-api#846]
When waitForElementVisible throws error, this error will be shown 6 times - https://prnt.sc/rsfk75
It's not reproduced when I run tests without nightwatch-api

nightwatch: "^1.3.4",
nightwatch-api: "^3.0.1"
browser: any
Tests are executed in the BrowserStack

**Comment by spnraju** [comment]
Hi @azinchenko91 Kindly note that you should be reporting this issue in [this ](https://github.com/nightwatchjs/nightwatch/issues)package.

Thank you!

**Comment by LucaLis** [comment]
Hi @spnraju. I think that it's a problem somewhere between nightwatch-api and core nightwatch lib. @azinchenko91 mentioned above that 

> It's not reproduced when I run tests without nightwatch-api

I came across similar poblem in my test env - I will try to isolate the issue and provide more details.
