### ISSUE TITLE
We add nightwatch-api to @leanup/cli

### ISSUE THREAD

**Issue by martinoppitz** [mucsi96/nightwatch-api#851]
Thank you all for this nice tool!

FYI: We added it to our @leanup/cli and we hope that we can provide that in the future.

Link: https://www.npmjs.com/package/@leanup/cli-core-e2e

**Comment by spnraju** [comment]
Hi @martinoppitz Thank you for letting us know!

**Comment by martinoppitz** [comment]
hi @spnraju 

last night I tryed to add the nightwatch headless option to your optionlist.

it does not work.

is there any way to propagate the headless option to nightwatch?

thanks

**Comment by spnraju** [comment]
Hi @martinoppitz , Are you looking to run tests in headless mode? We have a few examples inside the packages folder of the repo.

https://github.com/mucsi96/nightwatch-api/tree/master/packages

https://github.com/mucsi96/nightwatch-api/blob/master/packages/cucumber-selenium-example/nightwatch.conf.js#L28

Please let us know.
