### ISSUE TITLE
How to use page objects with nightwatch-api in step definitions file?

### ISSUE THREAD

**Issue by nishudixit** [mucsi96/nightwatch-api#853]
**This is my Step Definition file named 'ecosia-search.steps**

_import { Given, Then } from 'cucumber';
import { client } from 'nightwatch-api';

Given(/^I open ecosia search engine$/, async () => {
await client.url('https://www.ecosia.org/');
await client.waitForElementVisible('body');
});

Then(/^the title is "(.*)"$/, async text => {
await client.assert.titleContains(text);
await client.assert.visible('input[type=search]');
});

Then(/^I enter "(.*)" in search bar$/, async text => {
await client.setValue('input[type=search]', text);
await client.assert.visible('.button-search-icon');
});

Then(/^press ENTER key$/, async () => {
await client.setValue('input[type=search]', client.Keys.ENTER);
});

Then(/^search result contains "(.*)"$/, async text => {
await client.assert.containsText('.mainline-results', text);
});_

And below is my page object file i.e. HomePage.js

_module.exports = {
elements: {
searchBar: {
selector: 'input[type=search]',
},
searchButton: {
selector: '.button-search-icon',
}
}
};_

**Here is my nightwatch.conf.js file**

_const chromedriver = require('chromedriver');
const path = require('path');

module.exports = {
  src_folders : ["."],
  output_folder : path.resolve(__dirname, 'test-results'),
  custom_commands_path : "",
  custom_assertions_path : "",
  page_objects_path : path.resolve(__dirname, 'page-objects'),
  globals_path : path.resolve(__dirname, 'globals.js'),

  test_settings: {
    end_session_on_fail: false,
    default: {
      screenshots: {
        enabled: true,
        path: 'screenshots'
      },
      webdriver: {
        start_process: true,
        start_session: true,
        server_path: chromedriver.path,
        port: 4444,
        cli_args: ['--port=4444']
      },
      desiredCapabilities: {
        browserName: 'chrome',
        javascriptEnabled: true,
        acceptSslCerts: true
      },
    }
  }
};_

**How can i use the page objects in my step definition file?**

**Comment by nishudixit** [comment]
This is my **Step Definition file named 'ecosia-search.steps**

import { Given, Then } from 'cucumber';
import { client } from 'nightwatch-api';

Given(/^I open ecosia search engine$/, async () => {
  await client.url('https://www.ecosia.org/');
  await client.waitForElementVisible('body');
});

Then(/^the title is "(.*)"$/, async text => {
  await client.assert.titleContains(text);
  await client.assert.visible('input[type=search]');
});

Then(/^I enter "(.*)" in search bar$/, async text => {
  await client.setValue('input[type=search]', text);
  await client.assert.visible('.button-search-icon');
});

Then(/^press ENTER key$/, async () => {
  await client.setValue('input[type=search]', client.Keys.ENTER);
});

Then(/^search result contains "(.*)"$/, async text => {
  await client.assert.containsText('.mainline-results', text);
});

**And below is my page object file i.e. HomePage.js**

module.exports = {
    elements: {
        searchBar: {
            selector: 'input[type=search]',
        },
        searchButton: {
            selector: '.button-search-icon',
        }
      }
  };

**How can i use the page objects in my step definition file?**

**Comment by spnraju** [comment]
Hi @nishudixit, Kindly check the below link. It should be the same.

https://nightwatchjs.org/guide/working-with-page-objects/
