### ISSUE TITLE
Firefox with grid not working

### ISSUE THREAD

**Issue by mirzamusic** [mucsi96/nightwatch-api#859]
Even with your example show [here](https://github.com/mucsi96/nightwatch-api/tree/master/packages/cucumber-selenium-hub-example). 

Firs you will get an error that ie driver is not declared, and when you remove it from nightwach.cong.js and run `docker-compose up` tests will be started but all of them will fail with the first check.

test-machine_1  | Feature: DuckDuckGo
test-machine_1  | 
test-machine_1  |   Scenario: Searching DuckDuckGo
test-machine_1  |     Given I open DuckDuckGo search page
test-machine_1  |     Then the title is "DuckDuckGo — Privacy, simplified."
test-machine_1  | √ Testing if the page title equals 'DuckDuckGo — Privacy, simplified.' (43ms)
test-machine_1  |     And the DuckDuckGo search form exists
test-machine_1  | Testing if element <#search_form_homepage> is visible in 5000ms - expected "is visible" but got: "element could not be located" (5022ms)
test-machine_1  | undefined    ✖ failed
test-machine_1  |       Error while running "visible" command: Testing if element <#search_form_homepage> is visible in 5000ms - expected "is visible" but got: "element could not be located" (5022ms)
test-machine_1  |           at World.<anonymous> (/usr/src/app/step-definitions/steps.js:21:23)

**Comment by icloudphil** [comment]
@mirzamusic I believe this is not an issue with nightwatch-api, I have the same issue with just the `nightwatch` itself. I believe this was cause the fact that Firefox is using w3c protocol and some of the command, assertion from nightwatch was not supported. I have a test repo here to reproduce the issues. https://github.com/icloudphil/nightwatch-starter/issues/1, see if this is the same issue you are looking for.

However, I have been spend quite sometime to solve this issue by adding Firefox profile and so forth, it doesn't work, but running Firefox on local does work as expected, I am wondering what I missed.

**Comment by mirzamusic** [comment]
I also noticed that setting "webdriver" instead of "seleiun" configurations work better ( but some commands like moveTo not exists)

https://github.com/nightwatchjs/nightwatch-docs/blob/master/gettingstarted/configuration/config-webdriver-settings.md

**Comment by mirzamusic** [comment]
> @mirzamusic I believe this is not an issue with nightwatch-api, I have the same issue with just the `nightwatch` itself. I believe this was cause the fact that Firefox is using w3c protocol and some of the command, assertion from nightwatch was not supported. I have a test repo here to reproduce the issues. [icloudphil/nightwatch-starter#1](https://github.com/icloudphil/nightwatch-starter/issues/1), see if this is the same issue you are looking for.
> 
> However, I have been spend quite sometime to solve this issue by adding Firefox profile and so forth, it doesn't work, but running Firefox on local does work as expected, I am wondering what I missed.

  I also noticed that setting "webdriver" instead of "selenium" configurations work better ( but some commands like moveTo not exists)

https://github.com/nightwatchjs/nightwatch-docs/blob/master/gettingstarted/configuration/config-webdriver-settings.md

**Comment by icloudphil** [comment]
> > @mirzamusic I believe this is not an issue with nightwatch-api, I have the same issue with just the `nightwatch` itself. I believe this was cause the fact that Firefox is using w3c protocol and some of the command, assertion from nightwatch was not supported. I have a test repo here to reproduce the issues. [icloudphil/nightwatch-starter#1](https://github.com/icloudphil/nightwatch-starter/issues/1), see if this is the same issue you are looking for.
> > However, I have been spend quite sometime to solve this issue by adding Firefox profile and so forth, it doesn't work, but running Firefox on local does work as expected, I am wondering what I missed.
> 
> I also noticed that setting "webdriver" instead of "selenium" configurations work better ( but some commands like moveTo not exists)
> 
> https://github.com/nightwatchjs/nightwatch-docs/blob/master/gettingstarted/configuration/config-webdriver-settings.md

@mirzamusic Webdriver will be able to trigger Firefox locally and it rans fine, the issue probably has to do with how selenium hub is driving the automation use WebDriver. Maybe to do with `json wire protocol`, Chrome have no such issue as we specify w3c:false which basically is not using the new w3c protocol to execute UI automation. I am trying to see if other framework are able to handle the same situation and will report back.

**Comment by spnraju** [comment]
Thank you for adding the details @icloudphil !

@mirzamusic please let me know if this can be closed.
