### ISSUE TITLE
Why is Nightwatch-Cucumber not supporting sauce-labs to get test status pass/fail

### ISSUE THREAD

**Issue by 16580gs** [mucsi96/nightwatch-api#860]
Your issue may already be reported!
- Operating System and version (desktop or mobile):
- Link to your project:
Please search on the [issue track](../) before creating one.

## Steps to Reproduce (for bugs)

1. 2. 3. 4.

## Your Environment

- Version used:
- Browser Name and version:

**Comment by spnraju** [comment]
Hi @16580gs Please consider adding more details and raise the issue on respective repo. Kindly note that nightwatch-cucumber package is deprecated.
