### ISSUE TITLE
browserStack configuration for Selenium 4 doesn't work with nightwatch-api

### ISSUE THREAD

**Issue by ituradastra** [mucsi96/nightwatch-api#863]
Updating nightwatch.conf.js file according to selenium 4 browserStack changes doesn't work. 
The following error is returned: 
`VError: a BeforeAll hook errored, process exiting: cucumber.conf.js:11: BrowserStack access key is not set. Verify that "browserstack.key" capability is set correctly or set BROWSERSTACK_KEY environment variable (.env files are supported).`

## Expected Behavior
Updating to Selenium 4 should work with the examples provided on nightwatch (BrawserStack example configuration https://nightwatchjs.org/gettingstarted/configuration/) or on browserStack site  (https://www.browserstack.com/automate/capabilities?tag=selenium-4).

## Current Behavior
selenium 4 properties such as accessKey are not recognized.

## Steps to Reproduce (for bugs)
use the configuration file from nightwatch site and run some test

```
module.exports = {
  src_folders: [],

  webdriver: {
    keep_alive: true
  }

  test_settings: {
    default: {
      launch_url: 'https://nightwatchjs.org'
    },

    browserstack: {
      selenium: {
        host: 'hub-cloud.browserstack.com',
        port: 443
      },

      // More info on configuring capabilities can be found on:
      // https://www.browserstack.com/automate/capabilities?tag=selenium-4
      desiredCapabilities: {
        'bstack:options' : {
          local: 'false',
          userName: '${BROWSERSTACK_USER}',
          accessKey: '${BROWSERSTACK_KEY}',
        }
      }
    },

    browserstack.chrome': {
      extends: 'browserstack',
      desiredCapabilities: {
        browserName: 'chrome',
        chromeOptions : {
          w3c: false
        }
      }
    },

    'browserstack.firefox': {
      extends: 'browserstack',
      desiredCapabilities: {
        browserName: 'firefox'
      }
    },

    'browserstack.ie': {
      extends: 'browserstack',
      desiredCapabilities: {
        browserName: 'IE',
        browserVersion: '11.0',
        'bstack:options' : {
          os: 'Windows',
          osVersion: '10',
          local: 'false',
          seleniumVersion: '3.5.2',
          resolution: '1366x768'
        }
      }
    }
  }
```

## Your Environment
"cucumber": "6.0.5",
"nightwatch": "1.3.5",
"nightwatch-api": "3.0.1",

**Comment by icloudphil** [comment]
@ituradastra were you able to get it to work with current nightwatch without BrowserStack integration?
Looking at your config, try the following:

` key: process.env.BROWSERSTACK_ACCESS_KEY,`

we are using the following version "browserstack-local": "^1.4.5"

**Comment by spnraju** [comment]
Closing it as there is no response.
