### ISSUE TITLE
No tests defined using tags error after success test run

### ISSUE THREAD

**Issue by BinaryJava** [mucsi96/nightwatch-api#871]
## Expected Behavior

Test runs as usual, console returns that test has been run successfully

## Current Behavior

Test runs as usual but console returns **this error**: 

There was an error while starting the test runner:

Error: No tests defined! using source folder: D:\Users\*\Documents\*\*\features ; using tags: Demo_Test

### Nightwatch.conf.js:

require('nightwatch-cucumber')({
    cucumberArgs: ['--require', 'features/step_definitions', '--format', 'json:report/cucumber_report.json', 'features']
  })

module.exports = (function(settings) {
    settings.test_workers = false;
    return settings;
})(require('./nightwatch.json'));

### Nightwatch.json:

{
  "src_folders" : ["features"],
  "custom_commands_path" : "./lib/CustomCom/",
  "custom_assertions_path" : "",
  "page_objects_path" : "./pages",
  "globals_path" : "./lib/configset/globalModules.js",
  "live_output" : true,

  "test_workers": {
    "enabled": true,
    "workers": "auto"
  },
  
  "selenium" : {
    "start_process" : true,
    "server_path" : "./lib/drivers/selenium-server-standalone-3.141.59.jar",
    "start_session": true,
    "skip_testcases_on_fail": false,
    "log_path" : "",
    "host":"127.0.0.1",
    "port" : 4440,
    "cli_args" : {
      "webdriver.chrome.driver" : "./lib/drivers/chromedriver.exe"
    }
  },
    
  "test_settings" : {
    "chrome" : {
      "launch_url" : "http://localhost",
      "selenium_port"  : 4440,
      "selenium_host"  : "localhost",
      "silent": true,
      "screenshots" : {
        "enabled" : true,
        "on_failure": true,
        "path" : "./screenshots/"
      },
      "cli_args" : {
        "webdriver.chrome.driver" : "./lib/drivers/chromedriver.exe" 
      },
      "desiredCapabilities": {
        "browserName": "chrome",
        "javascriptEnabled": true,
        "acceptSslCerts": true,
        "chromeOptions": {
          "args" : [
            "disable-web-security",
            "ignore-certificate-errors",
            "--test-type",
            "start-maximized",
            "disable-infobars",
            "--disable-notifications"]
        }
      }
    }
  }
}

### Nightwatch.js:

require('./node_modules/nightwatch/bin/runner.js');

### package.json:

{
  "name": "A Name",
  "version": "1.0.0",
  "description": "A Description",
  "main": "nightwatch.js",
  "repository": {},
  "scripts": {
    "test": "nightwatch -c nightwatch_jenkins.js --env chrome -a Critical"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "cucumber": "4.0.0",
    "cucumber-html-reporter": "^4.0.2",
    "nightwatch": "0.9.20",
    "nightwatch-cucumber": "9.1.2"
  }
}

### Demo.feature:

@Demo
Feature: Demo suite

  @Demo_Test
  Scenario: Setting up Nightwatch framework
    
    Given User is on google homepage
    When User types Nightwatch into searchbar
    Then User can see the official Nightwatch website

### steps.js:

Given(/^User is on google homepage$/, () => {
    return GooglePage.navigate()
})

When(/^User types Nightwatch into searchbar$/, () => {
    return GooglePage.waitForElementVisible('@googleSearchBox').setValue('@googleSearchBox', ["Nightwatch",client.Keys.ENTER])
})

Then(/^User can see the official Nightwatch website$/, () => {
    return GooglePage.waitForElementVisible('@nightwatchURL')
})

## Context

It's a minor issue but is always something clients will pick up on thinking a fault is occurring.

**Comment by spnraju** [comment]
Hi @BinaryJava it seems like you have raised the issue on wrong package. nightwatch-cucumber is a archived package and i am afraid you wont get any support as of now. we really request you to consider nightwatch api migration.
