### ISSUE TITLE
Missing "Scenarios Outline" feauture with data-driven testing

### ISSUE THREAD

**Issue by masarani597** [mucsi96/nightwatch-api#873]
When do you plan to implement "Scenarios Outline" feature with passing of data from "Examples" like below ? 

Scenario Outline: eating
  Given there are <start> cucumbers
  When I eat <eat> cucumbers
  Then I should have <left> cucumbers

  Examples:
    | start | eat | left |
    |    12 |   5 |    7 |
    |    20 |   5 |   15 |

Is there any other supported way to pass data into your scenarios / steps other than mentioned above ?

**Comment by spnraju** [comment]
Hi @masarani597 the package should already be supporting the scenario outline. do you see any issues? would you mind sharing any sample repo?

**Comment by masarani597** [comment]
Hi spnraju, Thanks for your quick response. I was able to make it work with some modification on my side. Sorry about this.

I have two questions.

1. I noticed that this cucumber package for nightwatch is deprecated now ?
https://mucsi96.github.io/nightwatch-cucumber/
Is that true ? If yes, what is the recommended way to use cucumber with nightwatch ? We are about to start using this for our entire team and I hope we don't run into any issues.

2.  I have done lot of research but when it comes of page object pattern in nightwatch, there does not seem to be any way to use more than one page object inside a single test. Like linking and chaining of multiple page objects go jump from page to page and call their respective commands to do various activities (like how we do it in Java). Is it possible ? If yes, could you please kindly suggest me some resources ?

**Comment by spnraju** [comment]
@masarani597 Below is the response to your queries. But I am sorry for this much delay.

1) Nightwatch-api
2) You are talking about using chaining while navigating from one page to another? This is something I haven't tried before. I can update here if I get a chance to try it.
