### ISSUE TITLE
async await not working with client.getAttribute() command

### ISSUE THREAD

**Issue by nishudixit** [mucsi96/nightwatch-api#875]
Hello,

Here is my step from step definition file:

`import { Given, When, Then } from 'cucumber';`
`import { client } from 'nightwatch-api';`

`Then(/^I switch OFF the (.*) toggle$/, async (toggleName) => {
  const result = await client.getAttribute('.list-group-item', 'innerText');
  console.log('@@@@@@@@@@@@@@@@@@@@', result);
});`

When I run this code it prints undefined like this:
`@@@@@@@@@@@@@@@@@@@@ undefined`

Same thing is happening when using async await with `client.elements`

**Comment by gbkwiatt** [comment]
any  update on that ?

**Comment by spnraju** [comment]
Were you able to figure this out?

**Comment by spnraju** [comment]
Closing it as there is no response.
