### ISSUE TITLE
Allow API to start nightwatch runner with --verbose flag

### ISSUE THREAD

**Issue by jogoussard** [mucsi96/nightwatch-api#907]
## Expected Behavior

There should be a way to set the 'verbose' flag in the nightwatch runner, so as to get webdriver requests/responses logged.

## Current Behavior

AFAIK, the only logging related flag is the 'silent' mode allowed in the 'options' sent in `startWebDriver` but `silent: false` is the default and that doesn't log webdriver requests.

## Possible Solution

Allow options to have a `verbose: true` flag and in `client.js#createRunner` use:
```
function createRunner(options) {
  if (!runner) {
    runnerOptions = {
      env: options && options.env || getDefaultEnvironment(),
      configFile: options && options.configFile || getDefaultConfigFile(),
      silent: options && options.silent || false,
      verbose: options && options.verbose || false
    };
    runner = (0, _nightwatch.CliRunner)({
      env: runnerOptions.env,
      config: runnerOptions.configFile,
      verbose: runnerOptions.verbose
    });
...
```

## Context

Helpful when trying to debug webdriver issues. I am currently trying to track down why Safari is not performing the `moveTo` command and needed to make sure from Nightwatch perspective, the command was sent and successful.

## Your Environment
- Version used: 3.0.1
- Browser Name and version: Any - not related
- Operating System and version (desktop or mobile): Any - not related

**Comment by spnraju** [comment]
Have you tried this? https://github.com/mucsi96/nightwatch-api/blob/master/packages/cucumber-example/nightwatch.conf.js#L5

**Comment by jogoussard** [comment]
Ah - that was it. Thanks a lot!

**Comment by jogoussard** [comment]
Just to be a tad more clear:
```
module.exports = {
  silent: false,
  test_settings: {
    default: {
      webdriver: {
        start_process: true,
        port: 4444
      },
```
did not work on my setup but this (with silent in tes_setting:default section)
```
module.exports = {
  test_settings: {
    default: {
      silent: false,
      webdriver: {
        start_process: true,
        port: 4444
      },
```
did work, logging the requests/responses.

**Comment by spnraju** [comment]
> Ah - that was it. Thanks a lot!

You are welcome!



> Just to be a tad more clear:
> 
> ```
> module.exports = {
>   silent: false,
>   test_settings: {
>     default: {
>       webdriver: {
>         start_process: true,
>         port: 4444
>       },
> ```
> 
> did not work on my setup but this (with silent in tes_setting:default section)
> 
> ```
> module.exports = {
>   test_settings: {
>     default: {
>       silent: false,
>       webdriver: {
>         start_process: true,
>         port: 4444
>       },
> ```
> 
> did work, logging the requests/responses.

Ah.. I will check what is happening in our setup. Thank you for letting us know.
